### ISSUE TITLE
[建议]优化一下FreeSql.Tests测试项目

### ISSUE THREAD

**Issue by LambertW** [2881099/FreeSql#10]
问题
目前在未按照Mysql情况中运行Sqlserver测试，都会报mysql主库不存在的错误，执行一个单元测试需要18s。

建议
1. 短期方案，将`g.cs`中的不同数据库进行初始化分离。
2. 将`FreeSql`及`FreeSql.Tests`按照不同数据库进行拆分。

参见
[https://xunit.github.io/docs/shared-context](url)

代码示例，已测试通过
![image](https://user-images.githubusercontent.com/12291760/54207409-132f2f80-4515-11e9-9eb0-a4795a3886c4.png)
![image](https://user-images.githubusercontent.com/12291760/54207429-1a563d80-4515-11e9-9244-0d0c7effefb2.png)
![image](https://user-images.githubusercontent.com/12291760/54207435-1de9c480-4515-11e9-96f6-44a7d11d8c9e.png)

**Comment by LambertW** [comment]
未分离项目，出现类似以下问题，手误，请修改...

![image](https://user-images.githubusercontent.com/12291760/54210371-5344e100-451a-11e9-9fee-3d4d65d68c32.png)

**Comment by LambertW** [comment]
SqlServerExpression.ConverTest.cs
看到有一个Sql server的测试`ToChar`未通过？

![image](https://user-images.githubusercontent.com/12291760/54213333-32cb5580-451f-11e9-8e16-cce7f5fb0445.png)

**Comment by LambertW** [comment]
另外，建议使用 `ITestOutputHelper`进行output输出。

使用方式
``` c#
private readonly ITestOutputHelper output;

public sqlserverAdoTest(ITestOutputHelper output)
{
    this.output = output;
}

[Fact]
public void ToList() {
    var sb = new StringBuilder();
    var time = new Stopwatch();

    //var t31 = g.sqlserver.Select<xxx>().ToList();

    time.Restart();
    var t3 = g.sqlserver.Select<xxx>().ToList();
    time.Stop();
    sb.AppendLine($"Elapsed: {time.Elapsed}; ToList Entity Counts: {t3.Count}; ORM: FreeSql*");

    time.Restart();
    List<xxx> dplist1 = null;
    using (var conn = g.sqlserver.Ado.MasterPool.Get()) {
        dplist1 = Dapper.SqlMapper.Query<xxx>(conn.Value, "select * from song").ToList();
    }
    time.Stop();
    sb.AppendLine($"Elapsed: {time.Elapsed}; Query Entity Counts: {dplist1.Count}; ORM: Dapper");

    output.WriteLine(sb.ToString());
}
```

执行效果
![image](https://user-images.githubusercontent.com/12291760/54214573-732bd300-4521-11e9-9121-61e6ac109ff3.png)

**Comment by LambertW** [comment]
👍，Sql Server单元测试看上去覆盖挺全面的（虽然其他数据库一片红..）

我想我会抽时间再测试一些常规操作，验证一下是否适合我们内部使用~
感谢nicye的付出~

P.S. 因为上述部分建议涉及改动较大，若您接受相关建议，我可能没有太多时间帮忙进行逐一调整PR，抱歉！等后续有少部分需要调整，我再尝试提交PR操作~

**Comment by 2881099** [comment]
很棒，18秒可能是因为有几处批量插入1万条数据。

最终还是要分离项目，目前我一个人这样维护成本低很多。

单元测试我这边环境都有，全部通过的，每次发布前也会跑一遍测试。

你的建议很有效，我会采纳，谢谢
