### ISSUE TITLE
Aop.CurdAfter 能否把Where条件的参数添加进来

### ISSUE THREAD

**Issue by MJTucDi** [2881099/FreeSql#100]
fsql.Update<T>()
.Where(x => x.ID.Equals(id))
.Set(x => x.A, ‘123’)
.ExecuteAffrows();

fsql.Aop.CurdAfter += (s, e) =>{
当CurdType 为 Update时
e.DbParms只有.Set参数的 能否把Where中的参数也加进来
};

如果在CurdAfterEventArgs添加属性Dictionary key为参数名称 value为值就更好了
Dictionary<string,obj> Where 
Dictionary<string,obj> Set
Dictionary<string,obj> Insert

**Comment by 2881099** [comment]
where产生的是字符串值，没做参数化，实现不了

**Comment by 2881099** [comment]
set 更复杂，不能直接用一个object表示，因为有可能是set click=click+1，甚至可能是sql函数

**Comment by 2881099** [comment]
insert差不多也是这个原因

FreeSql的insert update操作可以是参数化，也可以不是参数化执行。

FreeSqlBuilder().UseNoneParameter(true) 可以全局控制IInsert IUpdate不使用参数化生成的sql语句，也可以局部使用 fsql.Inset().NoneParameter()，此时Aop.CurdAfter 里面的参数基本是没值

**Comment by MJTucDi** [comment]
好的，谢谢！我再想想别的办法。
