### ISSUE TITLE
是否支持Guid?类型？

### ISSUE THREAD

**Issue by wangdaguo68** [2881099/FreeSql#105]
![image](https://user-images.githubusercontent.com/13011816/66370128-9cd2ad00-e9d1-11e9-99d0-ccb1e0c5ddb9.png)
![image](https://user-images.githubusercontent.com/13011816/66370140-a6f4ab80-e9d1-11e9-891c-491394244754.png)
貌似不支持guid？类型

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/66373909-5b93ca80-e9dc-11e9-9659-3ebb0cad7303.png)

测试正常，在 #106 回复你吧，问题重复了，这个关掉
