### ISSUE TITLE
可否添加支持NotMapper特性？

### ISSUE THREAD

**Issue by wangdaguo68** [2881099/FreeSql#106]
由于业务需求，可能要讲efcore项目转成freesql，但是遇到两个问题。
1、notmapper特性不支持
2、Guid?类型不支持
望大佬，抽空解答一下

**Comment by 2881099** [comment]
notmapper 有，使用 [Column(IsIgnore = true)]

Guid? 类型支持

**Comment by wangdaguo68** [comment]
请问一下
1、[Column(IsIgnore = true)]在哪个包下面的，我这边识别不了，我用的三个包Freesql,Freesql.DbContext,FreeSql.Provider.MySql
2、我在实体上定义Guid?类型就报错，System.ArgumentException:“Expression of type 'System.Guid' cannot be used for assignment to type 'System.Nullable`1[System.Guid]'”
去掉就没问题

**Comment by 2881099** [comment]
1.在FreeSql下面，https://github.com/2881099/FreeSql/blob/master/FreeSql/DataAnnotations/ColumnAttribute.cs

2.这个待会我试下再回复你

**Comment by wangdaguo68** [comment]
谢谢~

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/66373909-5b93ca80-e9dc-11e9-9659-3ebb0cad7303.png)

测试正常

**Comment by 2881099** [comment]
方便将你的测试代码整理了下发出来吗？

**Comment by wangdaguo68** [comment]
![image](https://user-images.githubusercontent.com/13011816/66374288-40758a80-e9dd-11e9-8d8b-2bdaa9f7aaff.png)
![image](https://user-images.githubusercontent.com/13011816/66374432-8fbbbb00-e9dd-11e9-9426-a564338bb047.png)

**Comment by 2881099** [comment]
明白了，是 FreeSql.DbContext 报错，感谢反馈，待会发个版本更新这个问题

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e6%9b%b4%e6%96%b0%e6%97%a5%e5%bf%97
v0.10.8 更新一下试试，上面的连接是更新日志，可以关注一下

**Comment by wangdaguo68** [comment]
好的，谢谢
