### ISSUE TITLE
请问连接池是怎么维护的？没有看见释放连接池的地方，默认连接池是多少？

### ISSUE THREAD

**Issue by feijie999** [2881099/FreeSql#11]

**Comment by 2881099** [comment]
连接池在 ado.net 驱动的基本上，又包装了一次

内部完成所有使用和释放管理

例如postgresql的连接池类：https://github.com/2881099/FreeSql/blob/master/FreeSql/PostgreSQL/PostgreSQLAdo/PostgreSQLConnectionPool.cs

**Comment by 2881099** [comment]
连接池的大小，与驱动的配置一致；

忽略了驱动最小连接池大小，默认开启了预热连接的功能；

**Comment by feijie999** [comment]
连接池个数可否自己配置？如果项目采用微服务架构，那么就会存在多个FreeSql实例，如果默认一个实例占用50个连接池，那么postgresql的连接池很快就会用完，在postgresql连接池用完以后其他微服务将无法进行预热操作

**Comment by feijie999** [comment]
var pattern = @"Maximum\s*pool\s*size\s*=\s*(\d+)";无法匹配Server=127.0.0.1;Port=5432;Database=myDataBase;Userid=myUsername;
Password=myPassword;Protocol=3;Pooling=true;MinPoolSize=1;MaxPoolSize=20;
ConnectionLifeTime=15; 中的MaxPoolSize

**Comment by 2881099** [comment]
npgsql 能使用  MaxPoolSize 设置连接池大小吗。

pgsql 服务器默认最大连接数是 100个，可以改大一些。

**Comment by 2881099** [comment]
预热连接有好处。

如果没有预热，程序启动完成的瞬间，蜂拥而来的请求，会让程序卡死数秒。

**Comment by 2881099** [comment]
连接池大小设多大合适，这个根据使用情况定。

**Comment by feijie999** [comment]
[var pattern = @"Maximum\s*pool\s*size\s*=\s*(\d+)";](https://github.com/2881099/FreeSql/blob/aa2040a6293ceb876316542440840d49113e18cd/FreeSql/PostgreSQL/PostgreSQLAdo/PostgreSQLConnectionPool.cs#L65)
这一句是否有bug,正则表达式无法匹配到MaxPoolSize=20;

**Comment by 2881099** [comment]
没有bug，Npgsql 连接串中的最大连接数就是 maximum pool size=100

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/54264602-702af400-45ae-11e9-9203-cba22ebe5b21.png)

**Comment by 2881099** [comment]
http://www.npgsql.org/doc/connection-string-parameters.html

**Comment by feijie999** [comment]
谢谢，我还以为postgresql的连接池字符串格式和mysql的一样呢
![image](https://user-images.githubusercontent.com/23080599/54265270-e0864500-45af-11e9-8381-0d9ce1c7b91e.png)
