### ISSUE TITLE
FreeSql.Provider.Oracle的问题

### ISSUE THREAD

**Issue by lxh023** [2881099/FreeSql#111]
建议OracleUtils类中的QuoteSqlName方法，不要对表名及列名加引号，会造成报错。

**Comment by 2881099** [comment]
回头，我把Oracle改成默认为大写映射吧

**Comment by lxh023** [comment]
FreeSqlBulder(). UseAutoSyncStructure(true)
---这个使用了，会提示表已存在，回头把报错贴上来

**Comment by 2881099** [comment]
UseAutoSyncStructure

经常手机在线，回复错了
有个转大写的方法

**Comment by lxh023** [comment]
1、FreeSqlBuilder().UseSyncStructureToUpper，是这个方法吧？
我看了这里的说明： https://www.cnblogs.com/FreeSql/p/11569550.html
2、能否强制框架在oracle中不对表名、字段名使用双引号？即禁用加引号功能？

**Comment by 2881099** [comment]
引号不是关键问题所在，用 FreeSqlBuilder().UseSyncStructureToUpper 这个方法一样能解决大小写问题。

pgsql 恰好是反的，加引号的就不区分大小写，实际他都保存为“小写表名、字段名”了

oracle 不加引号，全保存为“大写表名、字段名”

UseSyncStructureToUpper、UseSyncStructureToLower 专门针对这两个库做的。

**Comment by lxh023** [comment]
我这边的oracle是10g的，加了引号后，做插入数据的时候会提示：ORA-00942 表或视图不存在；
比如说我设备一个表是test.test_table,但是加了一个引号后，oracle把“test_table”当成表名【带引号】，而不是当成在test用户下的test_table。所以在插入的时候 ，会提示表不存在。
 建议新口能否暴露一个开关，可以控制是否产生引号。因为我改了FreeSql.Provider.Oracle代码测试后是正常的。跟大小写没有关系。
   oracle的sql语句，一般情况下，不对表名或列名加引号

**Comment by 2881099** [comment]
new FreeSqlBuilder().UseSyncStructureToUpper(true)

**Comment by lxh023** [comment]
这个试过了，一样的提示，就是引号引起的

**Comment by lxh023** [comment]
OK，好像是可以了。但是还有另外一个问题。我UseLazyLoading(true)
如果改表名了，旧的表好像还在。设计上就是要保留的吗？

**Comment by 2881099** [comment]
UseLazyLoading(true) 和表名没关系

表名和 [Column(Name = "")] 有关系，表名改了，这里设置为数据库的表名就行。

**Comment by lxh023** [comment]
不好意思，打错了，上条应该是UseAutoSYncStructure（true）

**Comment by 2881099** [comment]
UseAutoSyncStructure(true) 没关系的，只要表名  [Column(Name = "")]  正确，不用改类名。

UseAutoSyncStructure(true) 在此之前自动创建的表，如果没有用 UseSyncStructureToUpper(true)，则这些表名依然是区分大小写。所以可以先删除旧的表，再使用 UseSyncStructureToUpper(true) 重新跑一遍表创建，以后就不存在大小写问题了。

**Comment by lxh023** [comment]
ok，谢谢感谢

**Comment by lxh023** [comment]
ok,非常感谢

**Comment by wbs-9760** [comment]
1.oracle数据库确实存在此问题，
2.UseAutoSyncStructure(true)：不是所有的项目都是用实体映射方式，当项目中dba是单独部门处理，编码由另一部门处理，或者其他决策，而且从代码角度来说这个应该可以提供入口来决定
3.经调试 代码问题出再  oracleUtils 的QuoteSqlName(params string[] name)  处，
