### ISSUE TITLE
关于错误处理

### ISSUE THREAD

**Issue by LuciusLu** [2881099/FreeSql#114]
是需要我自己try抓取错误再处理还是会直接返回失败？
还有就就是，比如插入一行数据，然后执行ExecuteAffrows，如果成功是返回1？失败返回什么？刚接触，问的比较傻，不好意思。

**Comment by 2881099** [comment]
需要自己try，ExecuteAffrows的返回值可以看成Command.ExecuteNonQuery，即影响的行数。wiki里面的crud文档api上有说明

**Comment by LuciusLu** [comment]
好的，加油，刚开始新项目把原本用的ORM转到你们这了。
