### ISSUE TITLE
有没一条语句同时Insert or Update？

### ISSUE THREAD

**Issue by LuciusLu** [2881099/FreeSql#115]
即存在时调用更新，不存在时插入。

**Comment by LuciusLu** [comment]
最好能支持批量的操作。

**Comment by 2881099** [comment]
有的在 FreeSql.Repository 库中定义的，文档 https://github.com/2881099/FreeSql/wiki/Repository

通用仓储可以做 crud 操作。

**Comment by 2881099** [comment]
仓储类除了🈶️ crud ，还实现了InsertOrUpdate方法。

和重要的状态跟踪，更新时只更新变化的属性。

**Comment by 2881099** [comment]
接口定义 https://github.com/2881099/FreeSql/blob/master/FreeSql.DbContext/Repository/Repository/IBasicRepository.cs

**Comment by LuciusLu** [comment]
嗯，好，谢谢
