### ISSUE TITLE
关于update方法的问题

### ISSUE THREAD

**Issue by mylovefly001** [2881099/FreeSql#121]
比如我有实体类：
`
 public class TestModel 
    {
        [Column(IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }

        public int GroupId { get; set; }

        public string UserName { get; set; } = String.Empty;

        public string PassWord { get; set; } = String.Empty;

        public string RealName { get; set; } = String.Empty;

        public int Status { get; set; }
    }
`

当我需要更新时，前端可能只传部分的参数。比如有可能只传：UserName ，PassWord 。也有可能只传UserName 。
当我更新的时候。我想最终生成的SQL语句是：
`
update xxx set `UserName `=xx,`PassWord `=xx where id=1;
`
或者
`
update xxx set `UserName `=xx where id=1;
`
也就是不想先查询该行的数据，只根据传过来的参数更新相关的字段。
不知道这时候Update怎么写,。。不知道能不能明白我说的意思 。

**Comment by 2881099** [comment]
引入仓储了没有，仓储专门做这类事情

**Comment by 2881099** [comment]
如果前端不传 olditem，直接 repo.Update(newitem) 也是行的，内部会先查一次数据库，然后作对比只更新变化的字段。

这个状态管理的功能是 FreeSql.DbContext/Repository 特有的功能，FreeSql.dll 里没有这个功能。

**Comment by mylovefly001** [comment]
可能是我技术不行，你说的方法试了没成功。
能不能直接支持匿名对象的更新？
例如这种写法：
DbContext.Mysql.Update<testModel>().Set(new  {
                UserName = testModel.Name,
                PassWord = testModel.Pid
            }).Where(t => t.Id == testModel.Id).ExecuteAffrows();

**Comment by 2881099** [comment]
你发的不是仓储用法，看看这个文档

https://github.com/2881099/FreeSql/wiki/Repository
https://github.com/2881099/FreeSql/wiki/DbContext

**Comment by 2881099** [comment]
你发的这个是FreeSql.dll原始用法

**Comment by mylovefly001** [comment]
OK了。感谢作者热心回答，希望freesql越做越好。
