### ISSUE TITLE
AddFreeRepository方法assemblies参数有什么用呢？

### ISSUE THREAD

**Issue by ainidajingzi** [2881099/FreeSql#134]
![image](https://user-images.githubusercontent.com/13308889/69202997-2dc6a780-0b7e-11ea-8307-13a171605ba5.png)
hi,
AddFreeRepository方法assemblies参数有什么用呢？
如果我不传值有什么影响呢？

**Comment by ainidajingzi** [comment]
找着源码看了看

**Comment by 2881099** [comment]
好的
