### ISSUE TITLE
Use without providing `UseConnectionString` for translating LINQ exp to sql

### ISSUE THREAD

**Issue by dehghani-mehdi** [2881099/FreeSql#135]
Hi,

Is there any way to use FreeSql to translate LINQ expression to SQL?

**Comment by 2881099** [comment]
Sorry, I can't help it. The UseConnectionString method sets the database type. Generating SQL statements is related to the database type.

**Comment by lovepoco** [comment]
https://github.com/2881099/FreeSql/wiki/%E6%9F%A5%E8%AF%A2
API ToSql

**Comment by dehghani-mehdi** [comment]
@lovepoco I'm looking for some way to translate LINQ expression to SQL without providing any DbContext or similar. e.g:

```
public class Foo {
    public int Id { get; set; }
}

Expression<Func<Foo, bool>> exp = (c) => c.Id > 10;

var sql = ToSql(exp);

expected result: WHERE Id > 10
```

**Comment by nodyang** [comment]
> @lovepoco I'm looking for some way to translate LINQ expression to SQL without providing any DbContext or similar. e.g:
> 
> ```
> public class Foo {
>     public int Id { get; set; }
> }
> 
> Expression<Func<Foo, bool>> exp = (c) => c.Id > 10;
> 
> var sql = ToSql(exp);
> 
> expected result: WHERE Id > 10
> ```

Do you want to convert an expression to sql instead of a database result set?

**Comment by 2881099** [comment]
```csharp
public class Foo {
    public int Id { get; set; }
}

Expression<Func<Foo, bool>> exp = (c) => c.Id > 10;

var connstr = @"Data Source=|DataDirectory|\db1.db";
IFreeSql fsql = new FreeSql.FreeSqlBuilder()
    .UseConnectionString(FreeSql.DataType.Sqlite, connstr)
    .UseAutoSyncStructure(true) //
    .Build();

var sql = fsql.Select<Foo>().Where(exp).ToSql();
```

expected result: 

```sql
SELECT a."Id" FROM "Foo" a WHERE a."Id" > 10
```

I hope it helps you。

**Comment by dehghani-mehdi** [comment]
@nodyang yes, I don't want to use any ORM, but want to use LINQ's powered API for some parts of my project. for example:

`Find<T>(Expression<Func<T, bool>>predicate, ...)`

Inside `Find` method I use/send raw SQL, I use reflection to provide requested fields and table name.

I already done `WHERE` part (I'm not sure about its quality though), but not `ORDER BY` or `JOIN` part. they are too heavy for me, I'm not that good with expression tree

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/blob/master/Providers/FreeSql.Provider.Odbc/Default/OdbcAdapter.cs

> dotnet add package FreeSql.Provider.Odbc

```csharp
class MyOdbcAdapter : FreeSql.Odbc.Default.OdbcAdapter
{
     public override char QuoteSqlNameLeft => ' '; // '[';
     public override char QuoteSqlNameRight => ' '; //']';
}

public class Foo {
    public int Id { get; set; }
}

Expression<Func<Foo, bool>> exp = (c) => c.Id > 10;

var connstr = @"...";
IFreeSql fsql = new FreeSql.FreeSqlBuilder()
    .UseConnectionString(FreeSql.DataType.Odbc, connstr)
    .Build();
fsql.SetOdbcAdapter(new MyOdbcAdapter());

var sql = fsql.Select<Foo>().Where(exp).ToSql();
```

expected result:

```sql
SELECT a. Id  
FROM  Foo  a 
WHERE (a. Id  > 10)
```

![image](https://user-images.githubusercontent.com/16286519/69221382-15708000-0bb2-11ea-85bd-787c5a4aaa02.png)

**Comment by nodyang** [comment]
> expression tree

The expression tree can handle your needs. You can refer to the source code of freeSql

**Comment by lovepoco** [comment]
translate Expression to sql is dependent on the database. If there is no clear context correspondence, it can only be an expression tree. If you want to understand the processing of the expression tree, please refer to https://github.com/2881099/freesql/blob/master/freesql/internal/utilsexpressiontree.cs
