### ISSUE TITLE
只会vb，报错未实现函数表达式 CompareString解析

### ISSUE THREAD

**Issue by cnxo2atjl** [2881099/FreeSql#140]
sqlite
Dim xxx = Fsql.Select(Of 部门).Where(Function(yy) yy.ID = 1).ToList
这个没问题

Dim xxx = Fsql.Select(Of 部门).Where(Function(yy) yy.部门名 = "财务").ToList

报错如下：
System.Exception
  HResult=0x80131500
  Message=未实现函数表达式 CompareString(yy.部门名, "财务", False) 解析
  Source=FreeSql

**Comment by 2881099** [comment]
好的，确实实现这个函数，问题是 c# 没得这个方法 CompareString，解决不了

.Where(Function(yy) yy.部门名.Equals("财务")).ToList

有没有这个方法？

或者看文档弄个自定义函数

## 自定义表达式函数(v0.11.23)

```csharp
[ExpressionCall]
public static class DbFunc
{
    //必要定义 static + ThreadLocal
    static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

    public static string FormatDateTime(this DateTime that, string arg1)
    {
        var up = context.Value;
        if (up.DataType == FreeSql.DataType.Sqlite)
            return $"date_format({up.Values["that"]}, {up.Values["arg1"]})";
        return "";
    }
    
    //...在此类中定义更多方法
}

var sql = fsql.Select<SysModule>()
    .ToSql(a => a.CreateTime.FormatDateTime("yyyy-MM-dd"));
//SELECT date_format(a."CreateTime", 'yyyy-MM-dd') as1 
//FROM "SysModule" a
```

context.Value.DataType 是 FreeSql.DataType 枚举类型，以便实现不同数据库的适配；

context.Value.Values 是 函数的各参数解析结果；

**Comment by pjy612** [comment]
感觉他得拿VB去实现这个，能搞的定吗？\_(:з」∠)\_

**Comment by fenfei100** [comment]
> sqlite
> Dim xxx = Fsql.Select(Of 部门).Where(Function(yy) yy.ID = 1).ToList
> 这个没问题
> 
> Dim xxx = Fsql.Select(Of 部门).Where(Function(yy) yy.部门名 = "财务").ToList
> 
> 报错如下：
> System.Exception
> HResult=0x80131500
> Message=未实现函数表达式 CompareString(yy.部门名, "财务", False) 解析
> Source=FreeSql

不要用等号比较，用 Equals 就没有问题。我之前就发现这个问题，按我们的思维 C# == 转到 VB.Net 用 = 就可以了，但是在 freesql 中没有实现转换，所以只能用 Equals

**Comment by 2881099** [comment]
现在用 vb 的人这么多吗

**Comment by fenfei100** [comment]
应该还是有吧，我觉得也不是多的问题，是个习惯问题吧。只能说 C#的大环境比VB.net 要好，加上微软的扶持。但是并不说就没什么有人用VB.net 了。

**Comment by 2881099** [comment]
未实现函数表达式 CompareString(yy.部门名, "财务", False) 解析

我说为什么表达式里不能用赋值。。。可能是考虑了 vb.net 那边的表达式赋值

**Comment by 2881099** [comment]
其实我最早也是写 vb6 入门的，后来慢慢就转到 c# 了

**Comment by fenfei100** [comment]
那是你转型成功了，我就失败了

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/70858191-06be8400-1f38-11ea-9128-c69fafb142ad.png)

```vb
Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")

        Dim fsql = New FreeSql.FreeSqlBuilder() _
            .UseConnectionString(FreeSql.DataType.Sqlite, "data source=testvb.db") _
            .UseAutoSyncStructure(True) _
            .UseMonitorCommand(Sub(cmd) Trace.WriteLine(cmd.CommandText)) _
        .Build()

        REM Microsoft.VisualBasic.CompilerServices.Operators.CompareString()

        Dim List1 = fsql.Select(Of Testvb).Where(Function(a) a.Id = 100).ToList()
REM SELECT a."Id", a."Title" FROM "Testvb" a WHERE (a."Id" = 100)

        Dim List2 = fsql.Select(Of Testvb).Where(Function(a) a.Title = "xxx").ToList()
REM SELECT a."Id", a."Title" FROM "Testvb" a WHERE (a."Title" = 'xxx')

        Dim List3 = fsql.Select(Of Testvb).Where(Function(a) a.Title <> "xxx").ToList()
REM SELECT a."Id", a."Title" FROM "Testvb" a WHERE (a."Title" <> 'xxx')

        fsql.Dispose()
    End Sub
End Module

Class Testvb
    Property Id As Integer
    Property Title As String
End Class
```
@fenfei100 @cnxo2atjl 
好多年没写 vb 代码了，下个版本将支持 string 的 = 和 <> 解析

**Comment by densen2014** [comment]
不用支持了, 反正已经摸通, :-)

**Comment by fenfei100** [comment]
标特否！
