### ISSUE TITLE
更新实体的问题

### ISSUE THREAD

**Issue by nbaiguo** [2881099/FreeSql#143]
var userAuth = new UserAuth();
userAuth.F_RoleType = _model.F_RoleType;
userAuth.F_UseType = _model.F_RoleType;

var returnValue = await _freeSql.Update<UserAuth>()
.Where(p => p.F_EmpId == _model.F_EmpId)
.SetSource(userAuth)
.ExecuteAffrowsAsync();

上面代码是更新数据，但empid不是主键。用这种方式执行会报错。

{
  "messages": [
    "An error ocurred."
  ],
  "developerMessage": {
    "ClassName": "System.Data.SqlClient.SqlException",
    "Message": "“)”附近有语法错误。",
    "Data": {
      "HelpLink.ProdName": "Microsoft SQL Server",
      "HelpLink.ProdVer": "11.00.3128",
      "HelpLink.EvtSrc": "MSSQLServer",
      "HelpLink.EvtID": "102",
      "HelpLink.BaseHelpUrl": "https://go.microsoft.com/fwlink",
      "HelpLink.LinkId": "20476",
      "SqlError 1": "System.Data.SqlClient.SqlError: “)”附近有语法错误。"
    },
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at FreeSql.Internal.CommonProvider.UpdateProvider`1.RawExecuteAffrowsAsync()\r\n   at FreeSql.Internal.CommonProvider.UpdateProvider`1.SplitExecuteAffrowsAsync(Int32 valuesLimit, Int32 parameterLimit)\r\n   at Account.API.Controllers.identityController.ChangeType(frm_ChangType _model) in C:\\dev\\erp\\src\\Services\\Account2.API\\Controllers\\identityController.cs:line 49\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146232060,
    "Source": "Core .Net SqlClient Data Provider",
    "WatsonBuckets": null,
    "Errors": null,
    "ClientConnectionId": "e1b53e4e-fd42-418d-93c5-a24726a9b7b2"
  }
}

{"code":500,"mes":"UPDATE [UserAuth] SET [F_SUId] = @p_0, [F_EmpId] = @p_1, [F_UserId] = @p_2, [F_ComId] = @p_3, [F_UseType] = @p_4, [F_OrgGuids] = @p_5, [F_RoleType] = @p_6, [F_RoleId] = @p_7 \r\nWHERE () AND ( F_EmpId='d3ec7e01-e85c-4024-b15e-d18795d2cefb' )","data":null,"record":null,"second":""}

调试是发现where里面是空的。

**Comment by 2881099** [comment]
SetSource 适合更新整个实体，有主键的实体。

换个方法

var returnValue = await _freeSql.Update()
.Where(p => p.F_EmpId == _model.F_EmpId)
.Set(a=> new UserAuth { 
F_RoleType = _model.F_RoleType,
F_UseType = _model.F_RoleType
 })
.ExecuteAffrowsAsync();

**Comment by chanaiguo** [comment]
> SetSource 适合更新整个实体，有主键的实体。
> 
> 换个方法
> 
> var returnValue = await _freeSql.Update()
> .Where(p => p.F_EmpId == _model.F_EmpId)
> .Set(a=> new UserAuth {
> F_RoleType = _model.F_RoleType,
> F_UseType = _model.F_RoleType
> })
> .ExecuteAffrowsAsync();

好像这样也是不行的。

**Comment by 2881099** [comment]
你试一下，😄

**Comment by chanaiguo** [comment]
> SetSource 适合更新整个实体，有主键的实体。
> 
> 换个方法
> 
> var returnValue = await _freeSql.Update()
> .Where(p => p.F_EmpId == _model.F_EmpId)
> .Set(a=> new UserAuth {
> F_RoleType = _model.F_RoleType,
> F_UseType = _model.F_RoleType
> })
> .ExecuteAffrowsAsync();


我现在只能写成这样。
            var up = _freeSql.Update<UserAuth>()
                .Where(p => p.F_EmpId == _model.F_EmpId);

            up.Set(a => a.F_RoleType, _model.F_RoleType);
            up.Set(a => a.F_UseType, _model.F_RoleType);

**Comment by 2881099** [comment]
.Set(a=> new UserAuth {
F_RoleType = _model.F_RoleType,
F_UseType = _model.F_RoleType
})

这种不成吗？

**Comment by chanaiguo** [comment]
> .Set(a=> new UserAuth {
> F_RoleType = _model.F_RoleType,
> F_UseType = _model.F_RoleType
> })
> 
> 这种不成吗？

不行的，连tosql()也不会出来的。

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/69843399-492e6280-12a2-11ea-94dc-f6454eabca3a.png)

看这个测试

**Comment by chanaiguo** [comment]
> ![image](https://user-images.githubusercontent.com/16286519/69843399-492e6280-12a2-11ea-94dc-f6454eabca3a.png)
> 
> 看这个测试

但你这个好像是id是主键的情况吧？我的并不是主键呢，只是一个条件。

**Comment by 2881099** [comment]
不用主键也可以，只有 where 条件存在，则执行
不存在，则直接返回 0

当没有 set 子句时，也是直接返回 0

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/69843521-d2de3000-12a2-11ea-935a-9f80e8c68b4b.png)

**Comment by chanaiguo** [comment]
> 不用主键也可以，只有 where 条件存在，则执行
> 不存在，则直接返回 0
> 
> 当没有 set 子句时，也是直接返回 0

你用的是sqllite的，我是mssql的，这个有关系吗？

**Comment by 2881099** [comment]
没有关系，里面走的代码是一样的

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/69843868-492f6200-12a4-11ea-87e2-62890b0cca95.png)

这个是 sqlserver 测试的

**Comment by chanaiguo** [comment]
> ![image](https://user-images.githubusercontent.com/16286519/69843868-492f6200-12a4-11ea-87e2-62890b0cca95.png)
> 
> 这个是 sqlserver 测试的

我等下再试下，昨天试了几次的确不行。

**Comment by chanaiguo** [comment]
> ![image](https://user-images.githubusercontent.com/16286519/69843868-492f6200-12a4-11ea-87e2-62890b0cca95.png)
> 
> 这个是 sqlserver 测试的

set里面事先赋值的实体不行的。
.Set(a => userAuth)
类似这样不行，你上面的那个是可以的。

**Comment by 2881099** [comment]
这个是表达式解析，不能直接Set实体，解不出要更新的字段

**Comment by chanaiguo** [comment]
> 这个是表达式解析，不能直接Set实体，解不出要更新的字段

如果是Set<T>呢？

**Comment by chanaiguo** [comment]
> 这个是表达式解析，不能直接Set实体，解不出要更新的字段

如果是Set T呢？

**Comment by 2881099** [comment]
SetSource 更新整个实体所有字段，但是需要实体有主键值，这种情况不用给为条件，它会自动把实体的主键作为条件。

**Comment by 2881099** [comment]
where set 任何为空，都不执行sql，安全考虑
