### ISSUE TITLE
fsql.Select<Model1>().Where(..xx)生成了错误的sql

### ISSUE THREAD

**Issue by yangbocheng** [2881099/FreeSql#146]
**-可能是用法有误，请大佬指正**

//按wiki-查询-利用导航属性-多表，使用导航属性--sqlite
`var ll = fsql.Select<Model2>().Where(o => o.m1sid == o.m1.Id).ToSql();`

**生成的错误sql--on-where处**
`SELECT a."Id", a."Name", a."m1sid", a__m1."Id" as4, a__m1."Name" as5 
FROM "Model2" a 
LEFT JOIN "Model1" a__m1 ON  
WHERE (a."m1sid" = a__m1."Id")`

类如下
```
class Model1
{
    [Column(IsPrimary = true, IsIdentity = true)]
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Model2> m2s { get; set; } //Model2-List
}

class Model2
{
    [Column(IsPrimary = true, IsIdentity = true)]
    public int Id { get; set; }
    public string Name { get; set; }
    public int m1sid { get; set; }
    public Model1 m1 { get; set; }
}
```

**Comment by 2881099** [comment]
[Navigate("m1sid")]
public Model1 m1 { get; set; }

加上这个试试

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb
参考：导航属性的配置文档

**Comment by yangbocheng** [comment]
加上特性后生成
`SELECT a."Id", a."Name", a."m1sid", a__m1."Id" as4, a__m1."Name" as5 
FROM "Model2" a 
LEFT JOIN "Model1" a__m1 ON a__m1."Id" = a."m1sid" 
WHERE (a."m1sid" = a__m1."Id")`
有效  谢谢大佬指正
