### ISSUE TITLE
添加/更新并返回值出错

### ISSUE THREAD

**Issue by fenfei100** [2881099/FreeSql#160]
ExecuteInserted / ExecuteUpdated 执行错误
数据库 mariadb 10 
我估计是没有 Returning 语句这个功能

SQLite 执行 ExecuteUpdated 也出错，错误提示大意为没有此属性或者过程

**Comment by 2881099** [comment]
是的， ExecuteUpdated ExecuteInserted ExecuteDeleted 这三个方法

在 sqlserver 有效，因为有 output 特性

在 postgresql 有效，因为有 returning 特性

其他数据库尽量别用这三个方法。

对于 ExecuteAffrows 和 ExecuteInserted 的适配，FreeSql.Repository 和 FreeSql.DbContext 有做判断。

伪代码如下：

```
if (有自增 && (sqlserver || postgresql)
    ExecuteInserted();
else
    ExecuteAffrows();
```

**Comment by 2881099** [comment]
插入，更新，尽量改用 FreeSql.DbContext 或 FreeSql.Repository 来做操作。

插入它有适配数据库类型，进行对应的执行操作。

更新它也有状态管理，执行更新实体的时候，只更新有变化的字段。

比如：
```csharp
var repo = fsql.GetRepository<Topic, int>();
var topic = repo.Find(1); //此时保存了 topic 的副本
topic.Title = "xxxx";
repo.Update(topic); //此时与副本对比，只更新 title 字段
```

通过 Repository 或 DbContext 查询的数据，会自动进入状态管理中（副本）。

也可以通过他们的 Attach 方法，手工设置副本，如下：

```csharp
var repo = fsql.GetRepository<Topic, int>();
var topic = new Topic { id = 1 };
repo.Attach(topic); //此时保存了 topic 的副本
topic.Title = "xxxx";
repo.Update(topic); //此时与副本对比，只更新 title 字段
```

**Comment by fenfei100** [comment]
谢谢，清楚了！
