### ISSUE TITLE
fsql.Ado.Query<object>在查询join时会报字典key重复异常

### ISSUE THREAD

**Issue by pardont** [2881099/FreeSql#162]
两张表，一个订单主档和一个订单明细档，在做join查询为object的时候，
fsql.Ado.Query\<object\>("select * from orderdetail left join ordermain on orderdetail.orderno=ordermain.orderno where ordermain.orderno='1001'");
会报错：
System.ArgumentException: 'An item with the same key has already been added. Key: OrderNo'

> 

 public class OrderMain
    {
        public string OrderNo { get; set; }
        public DateTime OrderTime { get; set; }
        public decimal Amount { get; set; }
    }
    public class OrderDetail
    {
        public string OrderNo { get; set; }
        public string ItemNo { get; set; }
        public decimal Qty { get; set; }
    }
> 

生成数据的代码：

            fsql.Insert<OrderMain>(new OrderMain { OrderNo = "1001", OrderTime = new DateTime(2019, 12, 01) }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1001", ItemNo = "I001", Qty = 1 }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1001", ItemNo = "I002", Qty = 1 }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1001", ItemNo = "I003", Qty = 1 }).ExecuteAffrows();
            fsql.Insert<OrderMain>(new OrderMain { OrderNo = "1002", OrderTime = new DateTime(2019, 12, 02) }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1002", ItemNo = "I011", Qty = 1 }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1002", ItemNo = "I012", Qty = 1 }).ExecuteAffrows();
            fsql.Insert<OrderDetail>(new OrderDetail { OrderNo = "1002", ItemNo = "I013", Qty = 1 }).ExecuteAffrows();

**Comment by 2881099** [comment]
@pardont 
select * from 

确实查了两次 OrderNo 字段，像这种情况应该怎么处理

**Comment by pardont** [comment]
@2881099 我觉得不报错，然后OrderNo以左侧的值，右侧的可以参考sqlite变成OrderNo_1，或者是前面补上表名也可以

**Comment by 2881099** [comment]
因为 Ado.net 返回的 Name 不是 OrderNo_1，才出现在的字典不能重复添加的错误。

**Comment by pardont** [comment]
嗯，这个好处理吗？报错的话总归不合适

**Comment by pardont** [comment]
@2881099 最低要求就是不报错，后面重复的部分重命名一下就挺好的

**Comment by 2881099** [comment]
我觉得，正确映射，比报错优先重要。

select * from 容易查到重复字段，即使我在返回数据的时候，重命名为 OrderNo_1，也映射不到对应的属性，要么就不处理它？不处理就不会报错

**Comment by pardont** [comment]
也可以，重复的部分基本都是一样的值，这样大概什么时候会有新版本更新呢，我试一下

**Comment by 2881099** [comment]
要等到元旦，统一更新。发布 1.0

暂时先不要用 select * from 可以解决当下问题，用指明字段

**Comment by pardont** [comment]
了解，辛苦了

**Comment by pardont** [comment]
@2881099 我升级了1.0.0，bug还在呀

**Comment by 2881099** [comment]
fsql.Ado.Query\<object\> 确实还会，上次没看清楚，是用的非 object

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/71707465-03c2ff00-2e25-11ea-8760-2c14f8ee202c.png)

\<object\> 解决了，测试通过

**Comment by pardont** [comment]
这效率，吃个午饭时间就解决了，厉害
