### ISSUE TITLE
net 4.7使用BaseEntity时抛出异常System.MissingFieldException:“找不到字段:“FreeSql.UnitOfWork.Current”。”

### ISSUE THREAD

**Issue by lolo77777** [2881099/FreeSql#163]

**Comment by lolo77777** [comment]
net core下正常，是不可以再net4.7下使用么，还是使用方式有不同呢

**Comment by 2881099** [comment]
BaseEntity 推荐用源码，目前有两个版本

[BaseEntity 纯净版源码(.Net 4.0).zip](https://github.com/2881099/FreeSql/files/3991497/BaseEntity.Net.4.0.zip)
[BaseEntity 纯净版源码.zip](https://github.com/2881099/FreeSql/files/3991498/BaseEntity.zip)

这个项目源码比较简单，推荐直接放到项目内使用。

**Comment by lolo77777** [comment]
> BaseEntity 推荐用源码，目前有两个版本
> 
> [BaseEntity 纯净版源码 (.Net 4.0).zip](https://github.com/2881099/FreeSql/files/3991497/BaseEntity.Net.4.0.zip)
> [BaseEntity 纯净版源码.zip](https://github.com/2881099/FreeSql/files/3991498/BaseEntity.zip)
> 
> 这个项目源码比较简单，推荐直接放到项目内使用。

好的，非常感谢，先试下。
