### ISSUE TITLE
能否支持non public Set属性和 non public 无参构造函数

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#164]
我在使用的[ABP](https://github.com/abpframework/abp)框架，遵从DDD规则，不允许外部对聚合根和实体进行修改，因此大部分的属性 Set都是protected的，并且大部分无参构造函数也是protected的。正好使用的EfCore也支持non public，倒也无可非议。
最近由于EfCore 3.0开始 不支持 sql server 2008 的row_number()那种分页的sql写法了，于是有了换一个ORM框架的想法，经过多方比较，觉得**FreeSql**是不二之选。遂开始从EfCore到FreeSql的代码迁移。
然后遇到了上述问题，由于FreeSql貌似暂不支持 non public Set属性和 non public 无参构造函数，迁移遇到阻碍。
抱着试一试的心态，引用了FreeSql的源码，然后做了少许修改。
把源码中所有的
`GetSetMethod()`
替换为了
`GetSetMethod(true) // true 表示允许non public`，
并且把FreeSql\FreeSql\Internal\UtilsExpressionTree.cs 文件的 1345行的
`var ctor = type.GetConstructor(new Type[0]) ?? type.GetConstructors().First();`
改为
`var ctor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[0], null) ?? type.GetConstructors().First();`

发现就支持简单的codefirst和查询使用了，后续估计其他的GetConstructor也得要进行修改。
擅自修改，也不知是否会有什么副作用。
想问一下，FreeSql是否会考虑官方支持这些修改？

---------------------------
还有个小问题
```
//基类
class IdEntity
{
    public virtual long Id{get; set;}
}
//子类
class IdentityUser : IdEntity
{
    public virtual string Name{get; set;}
    ......
}
```
codefirst生成的表，默认会把Id 生成到最后，相比之下，貌似EfCore就会先生成父类字段。
如果可以考虑把FreeSql\FreeSql\Extensions\FreeSqlGlobalExtensions.cs文件的GetPropertiesDictIgnoreCase方法中的
`var props = that.GetProperties();`
改为
`var props = that.GetProperties().GroupBy(p => p.DeclaringType).Reverse().SelectMany(p => p);`
就真的太棒了。可以少写很多.Position(X)

**Comment by 2881099** [comment]
1、GetSetMethod(true) ，因为使用了大量的 ExpressionTree 操作，如果属性不是 NonPublic 会不会报错（无法访问 protected 方法）

2、UtilsExpressionTree.cs 文件的 1345
疑问：强制得到 NonPublic 构造函数，不知道后面的 Expression.New(ctor) 会不会报错（无法访问 protected 方法）

3、GetPropertiesDictIgnoreCase 的顺序问题，这边改成和你一样了，统一到元旦发布1.0.0

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/71320285-229bca00-24e4-11ea-96d5-8942b0b33019.png)

把 GetConstructor 方法整理收缩了一下，整个解决方案目前只有很少的地方在使用

**Comment by 2881099** [comment]
搜索 GetConstructor 结果如下：

| 代码	| 文件	| 行 |	 列|
| -- | -- | -- | -- |
|        var ctorParms = _dicGetDefaultValueFirstConstructorsParameters.GetOrAdd(that, tp => tp. GetConstructors().FirstOrDefault()?.GetParameters());	| C:\Users\28810\Desktop\github\FreeSql\FreeSql\Extensions\FreeSqlGlobalExtensions.cs	|56	|97|
|            tp. GetConstructor(BindingFlags.Instance \| BindingFlags.Public \| BindingFlags.NonPublic, null, new Type[0], null) ??	|C:\Users\28810\Desktop\github\FreeSql\FreeSql\Extensions\FreeSqlGlobalExtensions.cs	|69	|17|
|            tp. GetConstructors(BindingFlags.Instance \| BindingFlags.Public \| BindingFlags.NonPublic).FirstOrDefault()) ??	|C:\Users\28810\Desktop\github\FreeSql\FreeSql\Extensions\FreeSqlGlobalExtensions.cs	|70	|17|
|            public static ConstructorInfo Constructor = typeof(RowInfo). GetConstructor(new[] { typeof(object), typeof(int) });	|C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\UtilsExpressionTree.cs	|1203	|74|
 |      static ConstructorInfo CtorDateTimeOffsetArgsTicks = typeof(DateTimeOffset). GetConstructor(new[] { typeof(long), typeof(TimeSpan) });	|C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\UtilsExpressionTree.cs|	1622|	86|
  |                  var ctor = dbContextType. GetConstructors().FirstOrDefault();	|C:\Users\28810\Desktop\github\FreeSql\FreeSql.DbContext\Extensions\DependencyInjection.cs	|18	|47|

**Comment by 2881099** [comment]
1、GetSetMethod(true)，刚才测试，好像没有访问限制的错误。那我这边也把 GetSetMethod 方法都改为 true 吧

**Comment by 2881099** [comment]
- 优化 实体基类的属性位置，优先排在最前面；
- 整理 实体类 Ctor 有构造函数的映射处理；[wiki](https://github.com/2881099/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae#dto-%E6%98%A0%E5%B0%84%E6%9F%A5%E8%AF%A2)
- 优化 实体属性，支持 protected set 属性；

提交了三项改动，大佬有空看下。

**Comment by tky753** [comment]
太效率了👍

**Comment by 2881099** [comment]
最近在准备 1.0 版本发布，元旦的时候发布
