### ISSUE TITLE
在工作单元中使用Update时是否可以在后面加where条件

### ISSUE THREAD

**Issue by landonzeng** [2881099/FreeSql#166]
_uow.GetGuidRepository<Table>().UpdateAsync(model)
在项目中使用工作单元的时候发现Update/UpdateAsync()方法前后都不能加Where(),是我用法不对么？

**Comment by 2881099** [comment]
对，仓储只能当实体主键值作条件。

已经传入了实体，还需要其他条件吗？

**Comment by landonzeng** [comment]
如果要加条件更新的话，只能使用select update的方式吧？

**Comment by landonzeng** [comment]
有时候需要批量更新有点不方便

**Comment by 2881099** [comment]
```csharp
var repo = _uow.GetGuidRepository<T>();
rep.UpdateDiy.SetSource(model).Where(a => ....).ExecuteAffrows();
```

ISelect.ToUpdate 建议在数据整理的场景下使用。

**Comment by landonzeng** [comment]
好吧，那如果需要根据条件批量更新的话，怎么处理比较好呢？

**Comment by 2881099** [comment]
批量更新有两种情况：

1、已经有实体列表了，使用 Repository.Update() 或者 IUpdate.SetSource() 都可以

2、没有实体列表，IUpdate.Where(a => a.socre > 100).Set(a => score + 5).ExecuteAffrows()，这种产生的SQL：

```sql
update t set score = score + 5 where score > 100
```

**Comment by landonzeng** [comment]
ok

**Comment by landonzeng** [comment]
IRepositoryUnitOfWork  下没有Repository.Update()或者IUpdate,就是说如果需要批量更新就不能用工作单元的模式了么？

**Comment by 2881099** [comment]
> UpdateDiy

UpdateDiy 的效果，和 fsql.Update\<T\>() 效果一样

**Comment by landonzeng** [comment]
好的

**Comment by landonzeng** [comment]
发现个问题，sql里面默认加了主键条件
![QQ截图20191223182211](https://user-images.githubusercontent.com/7336781/71352448-51cc3d00-25b1-11ea-8a23-bf15f9a13ba8.png)

**Comment by 2881099** [comment]
SetSource 是会按主键增加条件

**Comment by landonzeng** [comment]
要用SetRow吗？还能用其他的方法吗？

**Comment by 2881099** [comment]
SetSource 是更新整个实体，会自动增加主键值为 where 条件

SetRaw 是传 sql 文本进去更新，其实是 update set ... 这里的内容，需要手动设置条件

Set 是指定一个字段更新，Set(a => a.Code == "xxx"，需要手动设置条件

**Comment by landonzeng** [comment]
好的，总算搞明白了，
