### ISSUE TITLE
[建议]是否考虑增加InsertOrUpdate(List<TEntity> entities)的功能？

### ISSUE THREAD

**Issue by LambertW** [2881099/FreeSql#17]
同上，该实现也是比较常见的一个业务需求

**Comment by 2881099** [comment]
这个应该放在哪个类实现好，比较纠结，哈哈

**Comment by LambertW** [comment]
我看过`SqlSugar`的设计，有个独立的`ISaveable`实现，独立于IInsert/IUpdate。
在初始化的时候，再内部分离成IInsert/IUpdate。

[ISaveable](https://github.com/sunkaixuan/SqlSugar/blob/dev/Src/Asp.Net/SqlSugar/Interface/ISaveable.cs)

**Comment by 2881099** [comment]
这个功能已经增加，在FreeSql.DbContext内，仓储和DbSet都可以。

更新时忘了回复了

**Comment by LambertW** [comment]
谢谢，回头我看一下
