### ISSUE TITLE
实体关系一对多正确姿势是？

### ISSUE THREAD

**Issue by tiancai4652** [2881099/FreeSql#173]
public class BookLabel
    {
        [Column(IsPrimary = true)]
        public Guid ID { get; set; }

        public string FileName { get; set; }

        public virtual ICollection<Label> Labels { get; set; }
    }

    public class Label
    {
        [Column(IsPrimary = true)]
        public Guid ID { get; set; }
        public int Location { get; set; }
        public string Note { get; set; }

        public Guid BookLabelID { get; set; }
        public BookLabel BookLabel { get; set; }

        public Label(int location,string note="")
        {
            ID = Guid.NewGuid();
            Location = location;
            Note = note;
        }
    }

这是按照你的例子写的

执行代码

            var book = new BookLabel()
            {
                ID = Guid.NewGuid(),
                FileName = fileName,
                Labels = new List<Label> { new Label(lineIndex) }
            };
            MyContext.Insert<BookLabel>(book).ExecuteAffrows();

code first的时候只能自动生成BookLabel表，还是说只支持单表添加，查询的时候才支持关联实体查询？
另外，用特性Navigate的时候，参数填写什么？关联表主键吗？找了半天没个说明啊
另外2，用virtual属性表示延迟加载吗？你实际的例子里有virtual，但是说明页又没有，这个virtual代表什么？

第一次用，问题可能比较初级，见谅

**Comment by 2881099** [comment]
导航配置：
https://github.com/2881099/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb

级联保存：
https://github.com/2881099/FreeSql/wiki/%e8%81%94%e7%ba%a7%e4%bf%9d%e5%ad%98
需要使用 Repository 或 DbContext 或 BaseEntity

普通的 IInsert 即 IFreeSql.Insert 没有级联保存功能

virtual 表示延时加载：
https://github.com/2881099/FreeSql/wiki/%e5%bb%b6%e6%97%b6%e5%8a%a0%e8%bd%bd

**Comment by 2881099** [comment]
FreeSql + FreeSql.Provider.Xxx 组合，只能单表添加/更新，可以级联加载（贪婪）

FreeSql.DbContext + FreeSql.Provider.Xxx 组合，支持级联保存

FreeSql.DbContext 里面定义了通用 Repository 和 efcore 类似的 DbContext 使用习惯

**Comment by BI7PRK** [comment]
关于级联保存，在MySQL8.0 中测试没有成功。是哪里做得不对呢？ @2881099 
**FreeSql v3.5.303**
```C#
class User
{
    [Key]
    public int Id { get; set; }
    [Navigate(nameof(Id))]
    public UserExt Ext { get; set; }
}
class UserExt
{
    [Key]
    public int UserId { get; set; }
    [Navigate(nameof(UserId))]
    public User User { get; set; }
}
```
```C#
var entity = new User{ .... Ext = new UserExt{ ... } }
using var repo = _freeSql.GetRepository<User>();
repo.DbContextOptions.EnableCascadeSave = true; // 启用级联保存
var newEntity = await repo.InsertAsync(entity);
var newId =newEntity.Ext?.UserId ?? 0;
```

唯有 User 表有插入数据。

**Comment by 2881099** [comment]
@BI7PRK 你这个是一对一，建议用聚合根仓储

**Comment by BI7PRK** [comment]
> [@BI7PRK](https://github.com/BI7PRK) 你这个是一对一，建议用聚合根仓储

如何做？已尝试 `using var repo = _freeSql.GetRepository<User, UserExt>();` 问题依旧，看起来似乎是个BUG

**Comment by 2881099** [comment]
https://freesql.net/guide/aggregateroot.html

**Comment by BI7PRK** [comment]
> https://freesql.net/guide/aggregateroot.html

依然不成功。决定放弃。用 uow 写算了
