### ISSUE TITLE
DbConnectionPool中有一处编码错误会造成归还Sqlite链接时触发死循环

### ISSUE THREAD

**Issue by BaiCai9** [2881099/FreeSql#179]
测试环境方面,直接使用的是作者源码中的单元测试(需要修改g.cs中Sqlite链接生成方式使用UseConnectionFactory)
问题代码:
https://github.com/2881099/FreeSql/blob/master/FreeSql/Internal/CommonProvider/AdoProvider/DbConnectionPool.cs
![image](https://user-images.githubusercontent.com/51348251/71948279-7e679200-320a-11ea-80d1-f45ee50d2919.png)
作者可能是想写(Sqlite链接对象)obj.Value.Dispose();不小心写成了数据连接池中的对象释放obj.Dispose();
阅读了作者另一个项目SafeObjectPool后发现数据连接池中的对象释放是把自己归还到池中故触发死循环
https://github.com/2881099/SafeObjectPool/blob/master/SafeObjectPool/Object.cs
![image](https://user-images.githubusercontent.com/51348251/71948934-b53ea780-320c-11ea-9cec-41f5e3d86cb3.png)

**Comment by 2881099** [comment]
谢谢，我这就处理下

DbConnectionPool 是在使用 UseConnectionFactory 吧？
