### ISSUE TITLE
FreeSql.Generator生成实体主键没有IsPrimary

### ISSUE THREAD

**Issue by fishjimi** [2881099/FreeSql#182]
如果主键是自增的
属性中会有 IsIdentity = true
但是主键属性没有生成 IsPrimary= true
导致 _fsql.Update<xxx>().SetSource(entity).ExecuteAffrows();会报错

**Comment by 2881099** [comment]
收到，报什么错。

本来是想减少特性生成的，因为有约定主键。

约定：

当没有指明主键时，命名为 id 的字段将成为主键；（不区分大小写）

当没有指明主键时，自增列属性，会成为主键

**Comment by 2881099** [comment]
追问一下，使用的是什么数据库

**Comment by 2881099** [comment]
检查发现，DbFirst 获取 Primary 信息失败了。。最近的版本出现的，我修复一下

**Comment by fishjimi** [comment]
因为一些特殊情况我没有用约定ID
比如有时候指定了双主键，所以还是挺需要自动生成的

**Comment by 2881099** [comment]
这个问题是 去年 10.3 号增加索引 CodeFirst 改出来的 bug
问题已修复，还有个问题解决了再发布版本

**Comment by fishjimi** [comment]
好的，谢谢效率哥！

**Comment by 2881099** [comment]
dotnet tool install --global FreeSql.Generator --version 1.1.0-preview4

用这个更新命令工具，后面要加版本

**Comment by yezi34880** [comment]
sqlserver，主键名不叫ID，类型为字符串，但数据库设置了主键，dbfirst获取列时IsPrimary=false

**Comment by 2881099** [comment]
> sqlserver，主键名不叫ID，类型为字符串，但数据库设置了主键，dbfirst获取列时IsPrimary=false

dotnet tool update --global FreeSql.Generator --version 1.1.0-preview4-2

更新一下工具

**Comment by yezi34880** [comment]
> > sqlserver，主键名不叫ID，类型为字符串，但数据库设置了主键，dbfirst获取列时IsPrimary=false
> 
> dotnet tool update --global FreeSql.Generator --version 1.1.0-preview4-2
> 
> 更新一下工具

谢谢，下个版本啥时候发呀？

**Comment by 2881099** [comment]
> > > sqlserver，主键名不叫ID，类型为字符串，但数据库设置了主键，dbfirst获取列时IsPrimary=false
> > 
> > 
> > dotnet tool update --global FreeSql.Generator --version 1.1.0-preview4-2
> > 更新一下工具
> 
> 谢谢，下个版本啥时候发呀？

每个月发一个正式版本
