### ISSUE TITLE
UnitOfWork.GetOrBeginTransaction 将创建的DbTransaction赋值给Ado.TransactionCurrentThread

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#189]
DbContext或者Repository   GetOrBeginTransaction 创建的DbTransaction没有存进Ado，
在UseAutoSyncStructure(true)时，
![19XOZ4.png](https://s2.ax1x.com/2020/01/19/19XOZ4.png)
运行到**WithTransaction(XXX)**前就会触发SyncStructure()，
导致 SyncStructure失败。
能否这样改？
![1CPbyn.png](https://s2.ax1x.com/2020/01/19/1CPbyn.png)
```
               // 修改前
//                _tran = IsolationLevel == null ?
//                    _conn.Value.BeginTransaction() :
//                    _conn.Value.BeginTransaction(IsolationLevel.Value);
                // 修改后
                (_fsql.Ado as AdoProvider).BeginTransaction(TimeSpan.FromSeconds(60), IsolationLevel);
                _tran = _fsql.Ado.TransactionCurrentThread;
```

**Comment by 2881099** [comment]
UnitOfWork 这里的事务机制和 TransactionCurrentThread 不要样，UnitOfWork 主要给异步爱好者使用的。

这里确实可能和自动迁移发生死锁的可性。之前试过把事务对象传进去也不好使，最后我的解决办法是事务开启之前，先手工执行迁移相关实体。如果开启了自动迁移，这样用一下就可以触发 fsql.Select<t>()
