### ISSUE TITLE
单DbConnection情境下如何保持一直Open

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#191]
单元测试，用的Sqlite 的 :memory: 模式，单一DbConnection，中途Close()的话是不是会重置？
尝试`fSqlBuilder.UseConnectionFactory(DataType.Sqlite, () => connection)`这种写法，
但在**UnitOfWork** Commit 时会调用到 `_fsql.Ado.MasterPool.Return(_conn);`
![1iKDfA.png](https://s2.ax1x.com/2020/01/20/1iKDfA.png)
然后DbConnection 就被close并dispose了。

有没有啥解决办法？

**Comment by 2881099** [comment]
memory 模式有什么特征没，可以判断一下

**Comment by 2881099** [comment]
明白了，我兼容下

**Comment by tky753** [comment]
是否可以给FreeSqlBuilder增加一个UseDbConnection()

**Comment by tky753** [comment]
还有一个地方，也会Close DbConnection:
```
FreeSql\Providers\FreeSql.Provider.Sqlite\SqliteAdo\SqliteAdo.cs Line 23
```

**Comment by 2881099** [comment]
1.1.0-preview6 解决了该问题

方式一：
```csharp
.UseConnectionString(DataType.Sqlite, "Data Source=:memory:")
```

方式二：
```csharp
//定义单个连接对象
var conn = new SqliteConnection("Data Source=:memory:");

//FreeSqlBuilder 中
.UseConnectionString(DataType.Sqlite, () => conn)
```
