### ISSUE TITLE
能否和EF Core做一个对比？

### ISSUE THREAD

**Issue by nluyan** [2881099/FreeSql#192]
已经有了官方的ORM框架EF Core，为什么还要做一个同样功能的FreeSQL呢？我相信作者肯定有充分的理由，这也是我们最希望了解的，我们需要一份EF Core和FreeSQL的各个方面的详细对比资料。但似乎FreeSQL刻意回避了这点，似乎找不到相关资料，如果有的话，至少位置不明显，我觉得相关的说明应该放在最前面。

**Comment by 2881099** [comment]
从功能角度看，完全不一样，举个最简单的例子，悲观锁efcore是没有的。各取所需吧

从发展角度看，efcore 未来发展受官方推动，可变性高。freesql 未来发展受国内或个人或团队推动，更加接地气。参考其他需要的生态发展。

如果有兴趣可以按照wiki文档看看，自己体会过才知道差异性，别人说的你也体会不到，是这样吧？

freesql 个性功能：https://github.com/2881099/FreeSql/wiki/%E9%AA%9A%E6%93%8D%E4%BD%9C

**Comment by nluyan** [comment]
FreeSQL的介绍就只是：FreeSql is the ORM in .NetCore
我们都知道EF Core也是ORM
再往下看Features：
支持 CodeFirst 迁移，哪怕使用 Access 数据库也支持；
 支持 DbFirst 从数据库导入实体类，安装实体类生成工具；
 支持 深入的类型映射，比如pgsql的数组类型；
 支持 丰富的表达式函数，以及灵活的自定义解析；
 支持 导航属性一对多、多对多贪婪加载，以及延时加载；
 支持 读写分离、分表分库，租户设计，过滤器，乐观锁，悲观锁；
 支持 MySql/SqlServer/PostgreSQL/Oracle/Sqlite/达梦数据库/Access；

反正从介绍上看下来我个人是没有感受到FreeSQL和efcore从功能角度完全不一样。

当然我相信FreeSQL很强大也和EFcore完全不一样，我只是提出对文档方面提出建议。

**Comment by nluyan** [comment]
比如悲观锁efcore是没有的这个优势，首页的文档并没有强调出来，我建议把所有FreeSQL有的而efcore没有的或者freesql比efcore更强的点都在首页显眼部分详细列出来。我觉得dotneter开发者接触的第一个orm大概率是efcore，而采用freesql基本都会面临一个替换efcore的决策，这个说明能最直接告诉大家为什么要采用freesql。

**Comment by 2881099** [comment]
orm 很多，各有优势，efcore 表面光鲜痛点不少：

1. 产生的 sql，比较难看
2. 在各数据库的实现，是否平滑切换
3. 关于性能，如何做到简单得使用而不导致性能低下
4. 关于扩展性，efcore 虽然开源的，不过就国内的人很难参与贡献，没有了自己的设计想法

还有其他就不列举了

**Comment by 2881099** [comment]
> 比如悲观锁efcore是没有的这个优势，首页的文档并没有强调出来，我建议把所有FreeSQL有的而efcore没有的或者freesql比efcore更强的点都在首页显眼部分详细列出来。我觉得dotneter开发者接触的第一个orm大概率是efcore，而采用freesql基本都会面临一个替换efcore的决策，这个说明能最直接告诉大家为什么要采用freesql。

是的，大概率是 efcore，没办法因为它是官方出的。其他 orm 只能捡漏。

有些人，项目没开始做之前，还没碰不到 efcore 痛点，眼里他什么都最美丽。

还有一些人，他们是领导，不参与开发工作，一句话丢给下面，efcore 用的人多，微软出的，以后有保障。

**Comment by nluyan** [comment]
领导说得有道理啊，而且大多数人也都是这么想的，所以我才建议你在显眼的位置比较和列举一下FreeSQL相对于efcore的优势点，否则大家会觉得这就是一个和EFCORE功能一样的ORM

**Comment by 2881099** [comment]
好吧，我已经解释得非常清楚了，如果硬要说是一样我也没办法。

**Comment by doson2006** [comment]
楼主的意思，我觉得是 要你把FREESQL和EFCORE做个比较，然后列出FREESQL比EFCORE强的地方，然后让别人知道，增加使用FREESQL代替EFCORE的动力

**Comment by 2881099** [comment]
@doson2006 明白，做好自己就行。之前一度被喷，说我们黑efcore。反而让他们反感。

肯定不是一样的orm，差异性还是交给用户使用中自己发现吧。
