### ISSUE TITLE
能否支持主键字段根据PropertyInfo.Name == “id”自动确定

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#193]
FreeSql能够根据对应数据表的字段来自动判断Id的，
比如
```C#
class Song
{
   [Column(Name = "Id")]
    public string XXX{get; set;} //自动设置IsPrimary = true
}
```
但遇到
```C#
class Song
{
   [Column(Name = "XXX_ID")]
   public string Id { get; set; } //除非字段前缀和表名相同，否则不会自动设置IsPrimary = true
}
```
个人觉得，第二种情况一般会比第一种情况要多一些吧。
是否根据 string.Compare(PropertyInfo.Name, "id", true) == 0 来判断主键 会更合理一些？

**Comment by 2881099** [comment]
定好的规则再改会坑前面的人，Aop.ConfigEntityProperty 可以自定义规则，判断名称，设置 IsPrimary。

导航属性配置支持约定式，我现在基本不用它，除非做测试，实践中发现手动指明Navigate清晰很多。约定式简单，搞多了规则解释不清。

声明式繁琐，看起来直观清晰，不用理解规则。

谢谢提醒!
