### ISSUE TITLE
能否为ISelect提供OrderBy(string propertyName)的支持

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#197]
需要为order by做一个通用封装，传入属性名称，自动生成 order by sql语句。
尝试为`ISelect<>`写扩展方法，但因为需要一个 属性名-->字段名 的映射，
所以需要CodeFirst.GetTableByEntity(XXX)获取TableInfo后，再获取到字段名，然后通过`OrderBy(string sql, object parms = null)`来处理。
但不把ICodeFirst做成静态的话，每次都要先获取TableInfo，
然后调用 OrderByProp(string propName, TableInfo tableInfo)，还是有点冗余，
如果FreeSql能直接提供相应的支持，就方便多了。

**Comment by 2881099** [comment]
这个和 OrderBy(string sql, object parms = null) 有什么区别

OrderBy(“属性”)

**Comment by tky753** [comment]
能不能让封装的`TableInfo`被简单地获取到呢，比如让ISelect<T>实现类 **实现**一个接口
```C#
interface ISelectTableInfoInfoAccessor
{
   IReadOnlyList<SelectTableInfo> SelectTbInfos {get;}
}
class Select0Provider<> : ITableInfoInfoAccessor
{
   protected List<SelectTableInfo> _tables = new List<SelectTableInfo>();
    // 想要隐藏的话可以显示实现
    IReadOnlyList<SelectTableInfo> ITableInfoInfoAccessor.SelectTbInfos {get => _tables; }
}
```
然后就可以方便地写扩展方法了
```C#
public static ISelect<T> OrderByProps<T>(this ISelect<T> select,
            Dictionary<string, bool> sorts) where T : class
{
    var tableInfo = (select as ITableInfoInfoAccessor).SelectTbInfos[0].Table;
   ......
}
```

**Comment by 2881099** [comment]
IReadOnlyList 提示不支持 4.0，我们的默认要考虑 4.0 支持。

可以用下面的反射获取：

```csharp
var tbs = select.GetType().GetField("_tables", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(select) as List<SelectTableInfo>;
```

**Comment by tky753** [comment]
好的，问一下，我看 EfCore源码里很少用internal的，基本都是用 接口的显示实现来隐藏方法和属性的。反射调用和接口的显示实现，哪个效率更高呢？

**Comment by 2881099** [comment]
用接口的快，反射慢80倍左右。

个人不喜欢定义过多的接口，除非是常用的。人力有限，见谅。

**Comment by hessonsu** [comment]
OrderBy(string sql, object parms = null)
如果是表的排序字段是由前端web 控制的，有注入的风险吧？这里有无过滤下呢？

**Comment by 2881099** [comment]
> OrderBy(string sql, object parms = null)
> 如果是表的排序字段是由前端web 控制的，有注入的风险吧？这里有无过滤下呢？

是的，简单字段排序可以判断，order by count(xx) 类似这种表达式就不好判断了。所以我选择了让使用者自己判断，判方法：fsql.CodeFisrt.GetTableByEntity(typeof(实体类)).ColumnsByCs 这个是字典类型，对应实体的属性。
