### ISSUE TITLE
写库字符串截断问题

### ISSUE THREAD

**Issue by fishjimi** [2881099/FreeSql#198]
数据库字段类型是text
我C#代码是这样的
```
[Column(Name = "script")]
public string Script { get; set; }
```
之前我的脚本都保存在服务器里，工作得好好的，不知道从freesql哪个版本开始,
保存的时候发生了截断，导致我丢失了大量脚本，而且没有备份。气死我了

经测试，改成这样以后就不会发生截断了
```
[Column(Name = "script", DbType = "text")]
public string Script { get; set; }
```

**Comment by 2881099** [comment]
这个一直是这样，NoneParameter 不会截断。否则长度默认是255

也可以这样设置长度，适配了各种数据库类型。

[Column(Name = "script", StringLength = -1)]
public string Script { get; set; }
