### ISSUE TITLE
每次重启应用时会报“远程主机强迫关闭了一个现有的连接”

### ISSUE THREAD

**Issue by feijie999** [2881099/FreeSql#20]
![image](https://user-images.githubusercontent.com/23080599/54530547-0cddff00-49be-11e9-91e1-301d8fa10862.png)

**Comment by 2881099** [comment]
应该是开发环境链接池过大，不被服务器限制。

freesql做了连接预热功能，Pooling=true;Maximum Pool Size=5

开发环境设小一点应该可以解决你的问题

**Comment by feijie999** [comment]
连接字符串里面的Pooling=true;Maximum Pool Size=5设置为5就可以了吗？生成环境中配置多少比较合适呢？

**Comment by 2881099** [comment]
生产环境默认100，具体看情况分配
