### ISSUE TITLE
表达式树能否增强对动态构建where子句的支持

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#204]
想要实现类似于这个功能
```C#
var prefix  = "ab";
......

//以下参考自SqlKata
.Where("1=2")
.Where(q1 =>//实现 where ... AND  (xxxx)
{
    foreach (var prefix in prefix)
    {
        q1.OrWhereLike("TABLE_NAME", prefix + "%");  //实现  where ... OR XXX
    }

    return q1;
})
```
生成的sql语句类似于
```sql
select XXX from XXX
where 1=2 AND ([TABLE_NAME] like 'a%' OR [TABLE_NAME] like 'b%')
```

ISelect<>没有找到OrWhere()的方法，想要实现上述情景，现在貌似需要手动构建表达式树。
或者自己写sql字符串，然后调用.Where(string sql, object parms = null)

想要实现的话，可能需要
1. `Where(Func<ISelect<>, ISelect<>> callback) `  这里的Func不是Expression了，是不是不好实现
2. `OrWhere(......)`

**Comment by 2881099** [comment]
他们这样在用用 

> Expressesion<Func<T, bool>> orExp = a=> false;

orExp.Or(a=> ...);

select.Where(orExp);
