### ISSUE TITLE
Ado.Query<XX>()是不是不支持DataAnnotations

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#206]
需要用Ado.Query()查询一个存储过程，发现 接收实体定义的[Column(Name = "")] 没有生效。
看源码好像是直接 `type.GetFields()`
这里不能复用 Select 查询那一套吗

**Comment by 2881099** [comment]
是的，Ado里面的方法和特性没关系。

**Comment by tky753** [comment]
那有没有办法直接用ISelect 查询 **存储过程**呢? **数据库方法**我知道是可以直接查询的。
如果可以用ISelect直接查询 存储过程，就方便多了。

**Comment by 2881099** [comment]
ISelect 主要针对 Select 语句，如果执行的是存储过程那产生的 sql 意义很小了。

之前有人说 query 不要 特性，所以去掉了。

**Comment by tky753** [comment]
@2881099  `Ado.Query<T>()` 和 `ISelect<T>.ToList(a=>new T())`  为什么不复用最实体映射那部分的代码呢，感觉两者差不多吧？

**Comment by tky753** [comment]
那Ado.Query有其他自定义映射手段吗，感觉还是需要的吧？

**Comment by 2881099** [comment]
ISelect 产生的查询，基本都是精确生成的，一一对应。

Query 由于 Sql 太灵活，使用习惯差异化大，映射的时候比较麻烦，目前也是一对一精确映射，出错的时候容易发现问题。

> 那Ado.Query有其他自定义映射手段吗，感觉还是需要的吧？

在已存在的规则上改动，会影响老用户。让实体类属性名，和返回的数据一致？

**Comment by tky753** [comment]
一致的话，就要改成这种写法了：
```C#
public long XX_ID{ get; set; }
publis long Id => XX_ID;
```
就是查询的字段多了的话，有点不爽，毕竟这不是 视图或表，无法用代码生成器生成代码，都要手动录入。
