### ISSUE TITLE
fsql.Select<>().ToList(a => new DTO { }) 自动映射Dto字段至实体真实字段名而不是属性名是否合适

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#208]
个人感觉 Dto属性的名称 应该和 实体 的属性名 相同时自动 查询映射比较合理吧。
现在是和 数据表的字段名相同时才自动 查询映射。
总不能把真实字段名 传输到客户端吧，那不就暴露表结构了吗？

FreeSql是不是不推荐直接查询Dto，而是先查询 实体，再通过Automapper等工具来映射？
或者Dto也要加上[Column(Name="")]特性  ？

**Comment by tky753** [comment]
说错了，好像Dto 加上 [Column(Name="")]特性也没用

**Comment by 2881099** [comment]
dto很多人在用，推荐使用。这个还真是，没人提这个问题，有可能都接受了，或者他们属性名和表字段名相同。

**Comment by tky753** [comment]
现在的项目大多都属性名和表字段名相同了吧。我这个项目的数据库是10年前开始用的，以前都是直接查询返回DataTable的

**Comment by 2881099** [comment]
```csharp
if (dtTb.Table.ColumnsByCs.TryGetValue(dtoProp.Name, out var trydtocol) == false &&
    dtTb.Table.ColumnsByCs.TryGetValue(dtoProp.Name, out trydtocol) == false)
    continue;
```

我改成这样吧，第二个判断之前没有。
