### ISSUE TITLE
关于多表中子表count查询的问题

### ISSUE THREAD

**Issue by j4587698** [2881099/FreeSql#209]
1、如果最后tosql的时候(x => new XXXEntity())可以自动映射字段，但是如果我想加一个count字段，使用x => new XXXEntity(){Count = orm.Select<>.Where().Count()}，这样只会给新的赋值Count字段，有没有个选项可以直接把其他字段都赋值进去？而不是一个一个写。

2、orm.Select\<>这种只能这样写，我用BaseEntity，直接使用XXXEntity.Where(y => y.pId == x.Id)这样的写法会报x未定义，只能改成BaseEntity.Select\<XXXEntity>.Where(y => y.pId == x.Id)才行。这是BUG还是故意这样设计的？还是linq的限制？

3、有没有办法在直接在查出来的对象里直接添加某个字段？如果tosql里new的话应该时重新生成了一个新的对象，本来就是偷懒直接在entity里加忽略字段，重新new一个出来感觉就有点怪怪的。

**Comment by 2881099** [comment]
问题1，你需要仔细了解 dto 映射规则，你想达到情况2的结果，但是却用了情况2

```csharp
fsql.Select<Song>().ToList(a => new DTO { xxx = a.ext }) 
//情况1：附加所有映射，再额外映射 ext，返回 List<DTO>

fsql.Select<Song>().ToList(a => new Song { id = a.id }) 
//情况2：只查询 id，返回 List<Song>

fsql.Select<Song>().ToList(a => new { id = a.id }) 
//情况3：只查询 id，返回 List<匿名对象>

fsql.Select<Song>().ToList(a => new DTO(a.id))
//情况4：只查询 id，返回 List<DTO>

fsql.Select<Song>().ToList(a => new DTO(a.id) { xxx = a.ext })
//情况5：查询 id, ext，返回 List<DTO>

fsql.Select<Song>().ToList(a => new Song(a.id))
//情况6：查询 id，返回 List<Song>

fsql.Select<Song>().ToList(a => new Song(a.id) { xxx = a.ext })
//情况7：查询 id, ext，返回 List<Song>
```

**Comment by 2881099** [comment]
问题2，x是什么

问题3，使用dto映射情况1，可以解决

**Comment by j4587698** [comment]
@2881099 x就是要查询的主表，类似这样，有个ClassEntity，是分类表，一个ArticleEntity，是文章表，每个文章有一个所属分类。在分类表里有个IsIgnore = true的Count字段。
现在代码类似这样，
```
ClassEntity.Select.ToList(x => new ClassEntity{Count = BaseEntity.Orm.Select<ArticleEntity>().Where(y => y.pId == x.Id).Count()});
```
如果这样写，会报不可附加，未设置主键值。如果加上主键，就只会给主键与Count赋值。

问题2是指
```
ClassEntity.Select.ToList(x => new ClassEntity{Count = ArticleEntity.Where(y => y.pId == x.Id).Count()});
```
这样就会报使用了x但是未定义。

**Comment by 2881099** [comment]
ClassEntity.Select.ToList(x => new ClassEntity{Count = BaseEntity.Orm.Select\<ArticleEntity>().Where(y => y.pId == x.Id).Count()});

按照上面给的映射规则，把 new ClassEntity 换成其他类型即可。

不可附加是Repository内部抛出的，内部依赖主键做状态管理。

明白了，问题2可能是需要 ArticleEntity.Select.Where

**Comment by j4587698** [comment]
@2881099 谢谢，看了一下，的确问题2用Select.Where就可以了。
不可附加这个我看看，主要就是其他的都没做Dto，单独为它做有点烦。看看不多我就都赋值好了。

**Comment by 2881099** [comment]
class dto : ClassEntity {} 这样也行，dto映射规则中，情况1 情况2的区别是的new xx 这里的类型。
