### ISSUE TITLE
导航属性中父子关系能否快速根据父获取其所有下属子？

### ISSUE THREAD

**Issue by j4587698** [2881099/FreeSql#211]
借用自定义导航关系一节中父子的例子：
```
class Group {
    public int Id { get; set; } //Id、GroupId、Group_id

    public int ParentId { get; set; } //ParentId、Parent_id
    public Group Parent { get; set; }

    public ICollection<Group> Childs { get; set; }
}
```
假设有

- 一个Group Id=1,

- 一个Group Id=2, ParentId=1,
- 一个Group Id=3, ParentId=2,
- 一个Group Id=4,ParentId=1
现在我想获取Group Id=1的下属所有Group，包括子的子，即2，3，4都获取到，有什么快速的办法吗？
还是只能查Childs，然后循环Childs再找他的下属？

**Comment by 2881099** [comment]
faql.Select\<xxx>().IncludeMany(a=>a.Childs).ToList()

文档：https://github.com/2881099/FreeSql/wiki/%e8%b4%aa%e5%a9%aa%e5%8a%a0%e8%bd%bd#%E5%AF%BC%E8%88%AA%E5%B1%9E%E6%80%A7-onetomanymanytomany

**Comment by j4587698** [comment]
@2881099 这样只能加载一层把？或者用then？但是有可能子项有多少层。
这个需求类似是这样，部门A下属有部门B，部门B下属有部门C。部门C下属可能有部门D，这个是动态添加的。
现在希望知道部门A下有多少员工，这个员工包括部门A下属的BCD之类的所有部门的。

**Comment by 2881099** [comment]
IncludeMany 第二个参数就是 then 的效果，看下文档就知道了

**Comment by j4587698** [comment]
@2881099 then怎么能知道下面有多少层呢？层数是动态的，不可能编码的时候就携手then => then.IncludeMany(then => {})这样啊。
而且用then的话跟循环也就没什么区别了把？
主要是看sql有union all的方式可以实现类似的方法，就想看看Freesql里有没有类似的对应方式

**Comment by 2881099** [comment]
是的，层数动态的不行。

一般做法是一次查询所有层级的父子数据，再在内存处理。

怎么查询要看表，网上有多种父子表设计。如果是普通的 parentid 无法一次查询所有数据。

**Comment by 2881099** [comment]
faql.Select<xxx>().IncludeMany(a=>a.Childs, 
then => then.IncludeMany(b=>b.childs)
).ToList()

这样可以级联加载两层数据。

**Comment by j4587698** [comment]
@2881099 嗯，谢谢，不折腾花了，直接全拉内存算了。省心

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e6%9f%a5%e8%af%a2%e7%88%b6%e5%ad%90%e5%85%b3%e7%b3%bb\
新功能：父子关系表递归查询

可以解决这个问题。
