### ISSUE TITLE
实体属性和字段值对应不上

### ISSUE THREAD

**Issue by MrCCDreamer** [2881099/FreeSql#212]
![image](https://user-images.githubusercontent.com/36471920/74545639-2d268d00-4f84-11ea-9816-c4bd00b9f9a6.png)
![image](https://user-images.githubusercontent.com/36471920/74545703-50513c80-4f84-11ea-8bf2-a000577435bf.png)
user的name和loginname 返回来是对调的
求解

**Comment by 2881099** [comment]
手机看不到图片，能用文字描述吗

**Comment by 2881099** [comment]
查询语句，实体类发一下

**Comment by MrCCDreamer** [comment]
Public Class User
    Inherits AppBaseEntity(Of User, Guid)
    Private _name As String
    Private _login As String
    Private _password As String
    Private _sex As Integer
    Private _role_id As Integer
    Private _farm_id As String

    Public Property Name As String
        Get
            Return _name
        End Get
        Set(value As String)
            _name = value
            OnPropertyChanged()
        End Set
    End Property

    Public Property Login As String
        Get
            Return _login
        End Get
        Set(value As String)
            _login = value
            OnPropertyChanged()
        End Set
    End Property

**Comment by MrCCDreamer** [comment]
实体类 User 我数据库里 User 的Name 是 管理员 login是 admin 
查完回来的 user Name 变成admin ； login 变成 管理员了 
u= orm.Queryable(Of User).First

**Comment by 2881099** [comment]
user的name和loginname 返回来是对调的，没看见 loginname 属性，把查询语句也发一下

**Comment by MrCCDreamer** [comment]
我改了下名字 从loginname 变成 login了 我以为是都带name的原因 但是不是

**Comment by MrCCDreamer** [comment]
SELECT a.`CreateTime`, a.`UpdateTime`, a.`IsDeleted`, a.`Sort`, a.`Id`, a.`Login`, a.`Name`, a.`Password`, a.`Sex`, a.`Role_id`, a.`Farm_id` 
FROM `User` a 
limit 0,1

**Comment by 2881099** [comment]
把sql打印一下，

在 name login Set 里面给个断点，看看 value 的值

**Comment by MrCCDreamer** [comment]
加了断点了 在 name 和 login 的set 里 就是 name的value 变成 admin 了

**Comment by MrCCDreamer** [comment]
![image](https://user-images.githubusercontent.com/36471920/74549084-fbb0c000-4f89-11ea-889e-af88f79fa11e.png)

**Comment by 2881099** [comment]
set的时候，值就不对了吗？

**Comment by MrCCDreamer** [comment]
是的

**Comment by 2881099** [comment]
我起床开电脑了，加我 qq 远程我看一看

**Comment by 2881099** [comment]
qq: 2881099

**Comment by MrCCDreamer** [comment]
我找到原因了 
我犯了个愚蠢的错误 我用的INotifyPropertyChanged 通知属性更改的时候 没有加 propertyName 
然后通知属性改的时候 不知道为什么 顺序就乱掉了
我在别的地方 查询设置断点 结果是没问题的
  Public Property Name As String
        Get
            Return _name
        End Get
        Set(value As String)
            _name = value
            OnPropertyChanged("Name")
        End Set
    End Property

    Public Property Login As String
        Get
            Return _login
        End Get
        Set(value As String)
            _login = value
            OnPropertyChanged("Login")
        End Set
    End Property

**Comment by MrCCDreamer** [comment]
多谢 多谢

**Comment by 2881099** [comment]
好的，接着睡觉去。
