### ISSUE TITLE
请问怎么联表查询最近一条时间的列表

### ISSUE THREAD

**Issue by zanderzhg** [2881099/FreeSql#215]
people表

| id   | name |
| ---- | ---- |
| 1    | jack |
| 2    | mike |
| 3    | lily |

location表

| longitude  | latitude  | people_id | create_time             |
| :--------- | --------- | --------- | ----------------------- |
| 116.330603 | 32.859880 | 3         | 2020-02-22 17:14:35.409 |
| 116.330602 | 32.859882 | 1         | 2020-02-22 17:15:35.409 |
| 116.330604 | 32.859887 | 2         | 2020-02-22 17:16:35.409 |
| 116.330602 | 32.859887 | 2         | 2020-02-22 17:17:35.409 |
| 116.330603 | 32.859882 | 3         | 2020-02-22 17:18:35.409 |
| 116.330604 | 32.859880 | 1         | 2020-02-22 17:19:35.409 |
| 116.330602 | 32.859882 | 3         | 2020-02-22 17:20:35.409 |

请问怎么查询people表和子表最近时间的一条数据呢?

查询后的结果为
|id | name | longitude | latitude | create_time|
|-- | -- | -- | -- | --|
|1 | jack | 116.330604 | 32.859880 | 2020-02-22 17:19:35.409|
|2 | mike | 116.330602 | 32.859887 | 2020-02-22 17:17:35.409|
|3 | lily | 116.330602 | 32.859882 | 2020-02-22 17:20:35.409|

**Comment by 2881099** [comment]
fsql.Select\<people>()
.IncludeMany(a=>a.locations.Take(1), then=>then.OrderByDesc(b=>b.createtime))
.ToList();

**Comment by 2881099** [comment]
上面是一对多导航属性级联加载，执行两次sql查询。

**Comment by zanderzhg** [comment]
thx

**Comment by zanderzhg** [comment]
thx
