### ISSUE TITLE
当Mysql数据库里的字段名带有下划线时查出来为空

### ISSUE THREAD

**Issue by huangyebiaoke** [2881099/FreeSql#217]
比如avatar_url,comment_like等等之类的
差点没把我坑死😭

**Comment by 2881099** [comment]
怎么会，我这里大量使用了下划线。如何重现

**Comment by huangyebiaoke** [comment]
包信息
>  package id="FreeSql" version="1.1.0" targetFramework="net461"
>  package id="FreeSql.Provider.MySql" version="1.1.0" targetFramework="net461"

mysql版本信息
> mysql  Ver 14.14 Distrib 5.5.54, for Linux (x86_64) using readline 5.1

screentogif
![](http://pan.madeai.cn/?/pictures/issue_screenshot.gif)
录屏点[这里](http://pan.madeai.cn/?/video/issue_screenshot_BiliBili.mp4)

**Comment by 2881099** [comment]
你在用 Ado.Query\<T> 这个是纯属性名映射，此时 Colum 特性是不起作用的。

IAdo 的定义是 helper 的功能。

**Comment by 2881099** [comment]
建议用 fsql.Select\<T> 来查询数据

**Comment by 2881099** [comment]
```csharp
fsql.Select<User>().ToList();
```

**Comment by 2881099** [comment]
谢谢提醒，我把文档中加上了注意提醒的语句。

> 注意：Ado.Query 的实体特性是无效的，比如 [Column(Name = "xxx")] 无效

IAdo 作为 Helper 的意义存在，不能过深入挖掘，简单用用就好。

**Comment by huangyebiaoke** [comment]
好吧，第一次接触这个东西，还不太明白，不是bug就好，谢谢你的提醒🙏

发自我的iPad

在 2020年2月28日，12:33，2881099 <notifications@github.com> 写道：

﻿

你在用 Ado.Query<T> 这个是纯属性名映射，此时 Colum 特性是不起作用的。

IAdo 的定义是 helper 的功能。
