### ISSUE TITLE
使用DBFirst生成工具默认生成DBType特性后迁移数据库问题

### ISSUE THREAD

**Issue by teotw1314** [2881099/FreeSql#223]
使用DBFirst生成的实体类型大多类型默认生成有DBType,但该特性不具有通用性,即切换数据库后无法再使用自动迁移功能生成对应的表,因为类型无法对应,请问默认生成DBType是出于什么考虑呢?DBFirst生成实体类型时可否不生成不必要的DBType呢?

**Comment by 2881099** [comment]
当字段类型，和CodeFirst默认不相同时，就是出现 DbType。比如 varchar(100)，CodeFirst默认是255，又或者 oracle 的 number 类型。

https://github.com/2881099/FreeSql/wiki/%e7%b1%bb%e5%9e%8b%e6%98%a0%e5%b0%84#%E9%BB%98%E8%AE%A4%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84

**Comment by teotw1314** [comment]
明白了,感谢您的解答.
