### ISSUE TITLE
能否在ISelect插入执行前事件，可用于修改DbCommand内容

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#229]
类似于`UseMonitorCommand`中的`executing`参数，
区别在于`UseMonitorCommand`对量产的所有`ISelect`起效，
现在需要的是只对单一的`ISelect`起效，如果可以实现的话，就可由用户自由修改生成的sql语句

**Comment by 2881099** [comment]
换个解决办法，ISelect 有点重了

**Comment by 2881099** [comment]
ISelect\<T1\>.IQueryable\<T1\> AsQueryable();

将 ISelect 转换为 IQueryable，此方法主要用于扩展，比如：abp IRepository GetAll() 接口方法需要返回 IQueryable 对象。注意：IQueryable 方法污染较为严重，请尽量避免此转换

今天加的这个方法

**Comment by tky753** [comment]
AsQueryable()之后能否在 执行前修改DbCommand？
想要在执行前，把一段 join 语句替换成 outer apply，
虽然可以通过IAop.CommandBefore加事件，完事后再移除。
但如果IFreeSql多线程公用的话，好得加个判断避免其他线程也执行到了，稍微有些麻烦。

**Comment by 2881099** [comment]
这个问题的初衷是不是这个：https://github.com/2881099/FreeSql/issues/200

**Comment by tky753** [comment]
嗯
