### ISSUE TITLE
联合主键 BaseEntity Update 

### ISSUE THREAD

**Issue by MrCCDreamer** [2881099/FreeSql#234]
我有个类是联合主键 主键是 Id 和 FID 更新的时候出现问题显示我的实体主键未设置
我想知道 BaseEntity 联合主键的TKey怎么写

**Comment by 2881099** [comment]
先确认一下，你用的 BaseEntity 基类有没有定义 TKey Id 这种

```csharp
class MyClass : BaseEntity<MyClass>
{
      [Column(IsPrimary = true)]
      public int Id1 { get; set; }

      [Column(IsPrimary = true)]
      public int Id1 { get; set; }
}
```

试试这样

**Comment by 2881099** [comment]
如果 BaseEntity 源码玩的转，建议下载回来魔改，改成适合自己的项目中使用。

**Comment by MrCCDreamer** [comment]
System.Exception:“【延时加载】System.Windows.ResourceDictionary 编译错误：Exception has been thrown by the target of an invocation.

using System;
using FreeSql.DataAnnotations;
using System.Collections.Generic;
using System.Linq;

public class FreeSqlLazyEntity__System_Windows_ResourceDictionary : System.Windows.ResourceDictionary {
	private IFreeSql __fsql_orm__ { get; set; }

	private bool __lazy__Item = false;
	public override System.Object Item {
		get {
			if (base.Item == null && __lazy__Item == false) {
				throw new Exception("导航属性 System.Windows.ResourceDictionary.Item 解析错误，实体类型 System.Object 缺少主键标识，[Column(IsPrimary = true)]");
			}
			return base.Item;
		}
		set {
			base.Item = value;
			__lazy__Item = true;
		}
	}
}
”

**Comment by MrCCDreamer** [comment]
我把TKey去掉了

**Comment by 2881099** [comment]
实体类型 System.Object，发一下你的实体类

**Comment by MrCCDreamer** [comment]
<Index("uk_Primary", "Id,Lact", True)>
Public Class CowRecord
    Inherits BaseEntity(Of CowCard)
    Private _Id As Integer
    Private _Lact As Integer
    Private _Pen As Integer
    Private _BDAT As Date?
    Private _FDAT As Date?
    Private _DDAT As Date?
    Private _EDAT As Date?
    Private _ARDAT As Date?
    Private _MKDAT As Date?
    Private _BFDAT As Date?
    Private _USDAT As Date?
    Private _RC As Integer
    Private _DMLK1 As Integer
    Private _VetCount As Integer

    <Column(IsPrimary:=True)>
    Public Property Id As Integer
        Get
            Return _Id
        End Get
        Set(value As Integer)
            _Id = value
        End Set
    End Property


    <Column(IsPrimary:=True)>
    Public Property Lact As Integer
        Get
            Return _Lact
        End Get
        Set(value As Integer)
            _Lact = value
        End Set
    End Property

**Comment by MrCCDreamer** [comment]
![image](https://user-images.githubusercontent.com/36471920/76694918-c47e1d80-66b3-11ea-97d2-69cb7f9f73cf.png)

**Comment by MrCCDreamer** [comment]
![image](https://user-images.githubusercontent.com/36471920/76694936-d6f85700-66b3-11ea-8d30-87e70fac1292.png)
到Update那里就弹错了

**Comment by 2881099** [comment]
把完整的类发给我

**Comment by MrCCDreamer** [comment]
Imports FreeSql
Imports FreeSql.DataAnnotations
<Index("uk_Primary", "Id,Lact", True)>
Public Class CowRecord
    Inherits BaseEntity(Of CowCard)
    Private _Id As Integer
    Private _Lact As Integer
    Private _Pen As Integer
    Private _BDAT As Date?
    Private _FDAT As Date?
    Private _DDAT As Date?
    Private _EDAT As Date?
    Private _ARDAT As Date?
    Private _MKDAT As Date?
    Private _BFDAT As Date?
    Private _USDAT As Date?
    Private _RC As Integer
    Private _DMLK1 As Integer
    Private _VetCount As Integer

    <Column(IsPrimary:=True)>
    Public Property Id As Integer
        Get
            Return _Id
        End Get
        Set(value As Integer)
            _Id = value
        End Set
    End Property


    <Column(IsPrimary:=True)>
    Public Property Lact As Integer
        Get
            Return _Lact
        End Get
        Set(value As Integer)
            _Lact = value
        End Set
    End Property

    Public Property Pen As Integer
        Get
            Return _Pen
        End Get
        Set(value As Integer)
            _Pen = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property BDAT As Date?
        Get
            Return _BDAT
        End Get
        Set(value As Date?)
            _BDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property FDAT As Date?
        Get
            Return _FDAT
        End Get
        Set(value As Date?)
            _FDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property DDAT As Date?
        Get
            Return _DDAT
        End Get
        Set(value As Date?)
            _DDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property EDAT As Date?
        Get
            Return _EDAT
        End Get
        Set(value As Date?)
            _EDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property ARDAT As Date?
        Get
            Return _ARDAT
        End Get
        Set(value As Date?)
            _ARDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property MKDAT As Date?
        Get
            Return _MKDAT
        End Get
        Set(value As Date?)
            _MKDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property BFDAT As Date?
        Get
            Return _BFDAT
        End Get
        Set(value As Date?)
            _BFDAT = value
        End Set
    End Property

    <Column(DbType:="Date")>
    Public Property USDAT As Date?
        Get
            Return _USDAT
        End Get
        Set(value As Date?)
            _USDAT = value
        End Set
    End Property

    Public Property RC As Integer
        Get
            Return _RC
        End Get
        Set(value As Integer)
            _RC = value
        End Set
    End Property

    Public Property DMLK1 As Integer
        Get
            Return _DMLK1
        End Get
        Set(value As Integer)
            _DMLK1 = value
        End Set
    End Property

    Public Property VetCount As Integer
        Get
            Return _VetCount
        End Get
        Set(value As Integer)
            _VetCount = value
        End Set
    End Property


End Class

**Comment by MrCCDreamer** [comment]
![image](https://user-images.githubusercontent.com/36471920/76694998-8e8d6900-66b4-11ea-8ba6-d1a82d23bff8.png)

**Comment by 2881099** [comment]
```csharp
            BaseEntity.Initialization(g.sqlserver)
            Dim cowR As CowRecord = New CowRecord
            cowR.Id = 1
            cowR.Lact = 1
            cowR.VetCount = 1
            cowR.Save()

            cowR.VetCount += 1
            cowR.Update()

//线程14: INSERT INTO [CowRecord]([CreateTime], [UpdateTime], [IsDeleted], [Sort], [Id], [Lact], [VetCount]) VALUES(@CreateTime_0, @UpdateTime_0, @IsDeleted_0, @Sort_0, @Id_0, @Lact_0, @VetCount_0)

//线程14: UPDATE [CowRecord] SET [UpdateTime] = @p_0, [VetCount] = @p_1 
//WHERE ([Id] = 1 AND [Lact] = 1)
```

**Comment by MrCCDreamer** [comment]
咦 好奇怪 我再试一下 我抽出去弄个简单的

**Comment by 2881099** [comment]
Public Class CowRecord
Inherits BaseEntity(Of CowCard)

你这个继承写错了，CowRecord CowCard

**Comment by 2881099** [comment]
CowCard 类应该没定义主键吧

**Comment by MrCCDreamer** [comment]
……………………

**Comment by MrCCDreamer** [comment]
我错了 悄悄跪着爬走
