### ISSUE TITLE
CodeFirst 中 char 类型如何处理？

### ISSUE THREAD

**Issue by guliang21** [2881099/FreeSql#235]
实体属性类型为 char 时，貌似会被忽略掉。试了多种方式都没成功

**Comment by 2881099** [comment]
[Column(DbType = “char”)]

**Comment by guliang21** [comment]
我试出来了。要 `[Column(MapType = typeof(string), DbType = "char")]` 才行。为什么是 `MapType = typeof(string)` 呢？

**Comment by 2881099** [comment]
你的类型用的 char[] 吗，wiki 里面有映射文档表

**Comment by guliang21** [comment]
不，我实体类型是 char，数据库的类型希望是 char(1)，我是 SqlServer 数据库

**Comment by guliang21** [comment]
实体属性类型 char，不能直接映射到数据库的  char(1)。我也理解了需要用 `MapType = typeof(string)` 的用意。

如果可以直接映射，应该会更好
