### ISSUE TITLE
没有ToTreeList方法

### ISSUE THREAD

**Issue by gudufy** [2881099/FreeSql#237]
版本1.21，请问是要另外引入什么包吗？

**Comment by 2881099** [comment]
[关注更新日志](https://github.com/2881099/FreeSql/wiki/%e6%9b%b4%e6%96%b0%e6%97%a5%e5%bf%97)

这个是新增加的功能，会在 1.3.0 的时候发布

**Comment by 2881099** [comment]
v1.3.0-preview

- 调整 移除对 System.ValueType 的依赖，减少版本冲突问题；（目前 FreeSql.dll 无任何公用库依赖）
- 优化 IncludeMany 扩展方法对 T1 不自动迁移；
- 优化 BulkCopy 对可空类型的属性处理；#227
- 增加 ISelect`1 AsQueryable 方法，实现将 ISelect 转换为 IQueryable 类型；
- 优化 IAdo.Query 方法，当传入带主键特性的实体时，防止主键列为 null 时导致整行记录也为 null；
- 修复 UseGenerateCommandParameterWithLambda(true) 时子语句的参数没整合到主语句；#231
- 增加 ISelect.RawJoin 方法以便实现 Outer Apply 查询；#200


以下两项功能还没发布，上面的功能在 1.3.0-preview8 中发布了

- 增加 ISelect.ToTreeList 扩展方法查询数据，加工为树型 List；(注意：实体需要配置父子导航属性)
- 优化 TableInfo 元数据对 interface 实现类 IsVirtual 重写的判断（增加 IsFinal == false）；

**Comment by gudufy** [comment]
谢谢回复，希望能在文档中加以说明。

**Comment by 2881099** [comment]
一个月一个版本，中间会发布重要的 preview 版本
