### ISSUE TITLE
启动时间特别慢

### ISSUE THREAD

**Issue by sangeren** [2881099/FreeSql#24]
第一次启动程序需要20s左右，我想知道这么长的时间都做了什么事情？还是说我的电脑配置不够好？

谢谢

**Comment by 2881099** [comment]
一定连接的远程，开发环境将最大链接池设小一点，比如5

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/issues/11

因为默认做了预热，预热的作用参考上面的链接。

预热的数量，目前是按 max pool size 值，不设置默认是100，那么启动时将创建100个数据库连接，并打开。

开发环境下可以设小这个值，避免慢的问题。

**Comment by sangeren** [comment]
好的，我知道了，我改了下，确实快了。 谢谢
