### ISSUE TITLE
打扰了，Ado.ExecuteDataTable遇到的问题

### ISSUE THREAD

**Issue by lichen0210** [2881099/FreeSql#240]
Fsql = new FreeSql.FreeSqlBuilder()
              .UseConnectionString(FreeSql.DataType.Sqlite, @"Data Source=C:\Users\Administrator\Desktop\free.db;Attachs=free.db;Pooling=true;Max Pool Size=10")
              .UseAutoSyncStructure(true) //自动同步实体结构到数据库
              .Build(); //请务必定义成 Singleton 单例模式

DataTable t = Fsql.Ado.ExecuteDataTable("SELECT * FROM SONG", null);

在VS调试时，为什么变量t不能点击查看呢？

![第二行](https://user-images.githubusercontent.com/35231851/77036183-733e9880-69e9-11ea-8ade-728c32b88282.png)

**Comment by 2881099** [comment]
不清楚，应该是 vs debuger 问题

**Comment by lichen0210** [comment]
刚才引用了FreeSql项目源码，可以显示t了，谢谢大神
