### ISSUE TITLE
#if 预处理器指令貌似写错了

### ISSUE THREAD

**Issue by fenfei100** [2881099/FreeSql#249]
https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if

微软的文档中貌似 #if 没有 netcore 这个
在 FreeSql/Extensions/FreeSql.Extensions.BaseEntity 中的代码中用的是 #if netcore

但是类似 FreeSql/FreeSql.DbContext/UnitOfWork/UnitOfWork.cs 中用的是 #if netcoreapp

前者应该是错了，后者才是对的

**Comment by 2881099** [comment]
这个在 .csproj 中定义的，FreeSql.DbContext 和 FreeSql.Extensions.BaseEntity 定义得不一样

**Comment by 2881099** [comment]
FreeSql.DbContext
```xml
  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp31' or '$(TargetFramework)' == 'netcoreapp30' or '$(TargetFramework)' == 'netcoreapp22' or '$(TargetFramework)' == 'netcoreapp21'">
    <DefineConstants>netcoreapp</DefineConstants>
  </PropertyGroup>
```

FreeSql.Extensions.BaseEntity
```xml
  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp31' OR '$(TargetFramework)' == 'netcoreapp21'">
    <DefineConstants>netcore</DefineConstants>
  </PropertyGroup>
```

**Comment by fenfei100** [comment]
原来如此，了解了，谢谢
