### ISSUE TITLE
事务保存不成功

### ISSUE THREAD

**Issue by sangeren** [2881099/FreeSql#25]
![2](https://user-images.githubusercontent.com/8380824/54989281-28b35780-4ff3-11e9-86a6-96a41613a1d9.png)

如图所示，谢谢

**Comment by 2881099** [comment]
看上去没问题，控制台输出的内容是什么

**Comment by 2881099** [comment]
哦，你没有执行命令，Insert().ExecuteAffrows()

**Comment by 2881099** [comment]
文档 https://github.com/2881099/FreeSql/wiki/%e6%b7%bb%e5%8a%a0

**Comment by 2881099** [comment]
看下面API说明部分

**Comment by sangeren** [comment]
好吧我知道了，之前一直用ef。 谢谢了
