### ISSUE TITLE
属性设置 ServerTime 特性后，SQL 语句参数为 null

### ISSUE THREAD

**Issue by guliang21** [2881099/FreeSql#254]
设置 ServerTime 特性后，打印 SQL 语句参数时，这个参数会是 null。过滤了就好了。这算 BUG 不

**Comment by 2881099** [comment]
参数 null，是什么意思

**Comment by guliang21** [comment]
`Aop_CurdBefore` 事件中，e.DbParms 中的参数可能为 null

**Comment by 2881099** [comment]
是的，因为标记这个特性，sql是

insert t (....) values (..., getdate())

所以没参数

**Comment by guliang21** [comment]
可以考虑处理一下

**Comment by guliang21** [comment]
这个问题还是建议处理一下，参数值可以就写成 getdate()。

如果不做这个处理，在日志记录 SQL 语句时，目前给的示例是会报错。

**Comment by 2881099** [comment]
```csharp
/// <summary>
/// 执行的 SQL
/// </summary>
public string Sql { get; }
/// <summary>
/// 参数化命令
/// </summary>
public DbParameter[] DbParms { get; }
```

CurdBeforeEventArgs 属性是这样定义的，getdate() 这个没地方放了，能描述下是什么需求吗

**Comment by niening314** [comment]
> ```cs
> /// <summary>
> /// 执行的 SQL
> /// </summary>
> public string Sql { get; }
> /// <summary>
> /// 参数化命令
> /// </summary>
> public DbParameter[] DbParms { get; }
> ```
> 
> CurdBeforeEventArgs 属性是这样定义的，getdate() 这个没地方放了，能描述下是什么需求吗

如果实体属性设置了ServerTime
```cs
[Column(ServerTime = DateTimeKind.Utc)]
public DateTime createtime { get; set; }
```
在使用Aop时 e.DbParms集合中会出现null元素,导致报错
```cs
freesql.Aop.CurdBefore += (s, e) =>
            {
                Console.WriteLine($"params:\r\n{string.Join("\t\r\n", e.DbParms.Select(i => $"{i.ParameterName}:{i.Value}"))}");
            };
```
如果使用?操作符，会出现 “:” 无意义字符
```cs
i => $"{i?.ParameterName}:{i?.Value}"
```
他的意思是让你考虑一下 不将其加入到 Aop的 e.DbParms集合中

**Comment by 2881099** [comment]
好的
