### ISSUE TITLE
获取部分列

### ISSUE THREAD

**Issue by sangeren** [2881099/FreeSql#26]
使用codefirst，repository
获取某个实体列表时，不想过去全部的字段，
能不能指定某个表，然后用一个定义了部分字段的类来获取列表，

谢谢了，最近有点忙，没时间去探索。

**Comment by 2881099** [comment]
repos.Select.ToList(a=> a.Id)

可以这样子用，如果多个字段，可以用匿名类

**Comment by sangeren** [comment]
如果使用匿名类会有一些问题，比如api文档
没有其它的方式吗，还是需要自己实现

**Comment by 2881099** [comment]
你应该是想建一个 DTO 类。这个可能支持，我不确定，待我测试下反馈。

另外：匿名类也可以写注释

![image](https://user-images.githubusercontent.com/16286519/55391458-fb732600-556b-11e9-998d-7653ea446d3f.png)

像这样写接口文档，swagger 可以识别，注释内是 markdown 格式。

**Comment by sangeren** [comment]
是想直接返回Dto，不想手动复制或mapper，
因为我想最直接就是从数据库取回Dto列名

**Comment by 2881099** [comment]
```csharp
var testDto1 = Fsql.Select<Song>().Limit(10).ToList(a => new TestDto { iddd = a.Id, name = a.Title });

class TestDto {
	public int iddd { get; set; }
	public string name { get; set; }
}
```

能接受这种吗，仍然需要配对字段。
另外：之前已经支持直接加载整个表对象（导航对象）。

.ToList(a => a);
.ToList(a => a.Category);
.ToList(a => new { a, a.Category })

**Comment by 2881099** [comment]
new TestDto 这种用法现有的版本不支持，我刚才已经测试通过。
预计 4.4 下班前会发布版本

**Comment by 2881099** [comment]
var testDto1 = Fsql.Select<Song>().Limit(10).ToList(a => new TestDto { id = a.Id, name = a.Title });
var testDto2 = Fsql.Select<Song>().Limit(10).ToList(a => new TestDto());
var testDto3 = Fsql.Select<Song>().Limit(10).ToList(a => new TestDto { });
var testDto4 = Fsql.Select<Song>().Limit(10).ToList(a => new TestDto() { });

这四种都支持，下面三种，会查找 Song 与 TestDto 相同的属性。如果一个都不相同时，抛出异常

**Comment by sangeren** [comment]
我测试 是可以的，谢谢。

**Comment by sangeren** [comment]
.FirstAsync()
这个方法也希望能重载上面的参数！

谢谢

**Comment by 2881099** [comment]
好的，已记录
