### ISSUE TITLE
where Lambda 属性类型为 Guid 时不能执行

### ISSUE THREAD

**Issue by sangeren** [2881099/FreeSql#28]
提示不支持的表达式，我想知道 为什么不支持guid类型，同字符串一样实现有问题吗？

然后还有一个问题，我使用mysql数据库，打包时打了一堆别的数据库dll，能不能不同数据库独立发包？

**Comment by 2881099** [comment]
问题1 where怎么写的

问题2 你应该用的是netframework？由于是netstandard库，是会比较多小包。未来是这个趋势，按数据库拆分其实不会少几个dll。

**Comment by sangeren** [comment]
await _postCategoryRepository.Select.Where(p => p.ParentId.Equals(Guid.Empty)).ToListAsync();

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%87%BD%E6%95%B0
这里是表达式解析的列表


可以直接用 = 判断，equals没支持，回头我支持一下，谢谢提醒

**Comment by sangeren** [comment]
“然后还有一个问题，我使用mysql数据库，打包时打了一堆别的数据库dll，”

这个问题是样的，我部署到docker中，每次 restore project 时会去拉所以引用的包，
那天网不好，每次都是断在 freesql的还原，然后我看了它引用了一些别的数据库dll，所以我想有了这个想法。

**Comment by sangeren** [comment]
.Where("ParentId = ?ParentId", new { ParentId = Guid.Empty })

这是我之前找到方式，不知道你说的是这个意思不。

**Comment by 2881099** [comment]
了解了，看来还是得拆。

不过到时候会暴露一些，对外部没多少意义的方法和类。

**Comment by 2881099** [comment]
> .Where("ParentId = ?ParentId", new { ParentId = Guid.Empty })
> 
> 这是我之前找到方式，不知道你说的是这个意思不。

这种也可以，我说的是 .Where(p => p.ParentId == Guid.Empty)

**Comment by 2881099** [comment]
我现在把 Equals 改成和 == 一样的行为了。

当右表达式值为 NULL 时，会变为 ParentId is null

**Comment by 2881099** [comment]
is null, is not nul 这个行为之前就有

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/55571811-dc75bf00-5738-11e9-92fd-08382d966984.png)

谢谢你的提醒

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/issues/55
现在按小包拆分发布了，谢谢
