### ISSUE TITLE
未实现函数表达式 p.IsDeleted.Equals(False) 解析

### ISSUE THREAD

**Issue by sangeren** [2881099/FreeSql#29]
IsDeleted 是 bool 类型

谢谢

**Comment by 2881099** [comment]
兄弟，软删除功能怎么不使用全局过滤器

**Comment by 2881099** [comment]
问题收到，我测试一下

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/55792149-98950800-5af2-11e9-9a1b-0553931f8d6e.png)

哦哦，同上次一样的问题。属于已解决未发布nuget。
稍后我先发布一次版本吧，v0.4.9（4月9号）

**Comment by sangeren** [comment]
好的，后面我看下 全局过滤器
