### ISSUE TITLE
请问一下连接方式与释放

### ISSUE THREAD

**Issue by LoveAuggie** [2881099/FreeSql#50]
对于Sqlite的数据库，连接使用之后，请问一下，该怎么关闭连接呢？

**Comment by 2881099** [comment]
正确使用方式，是建一个 IFreeSql，然后重复使用，常驻内存。

然后如果真的想释放连接，可以调用 IFreeSql.Dispnse() 方法

**Comment by LoveAuggie** [comment]
感谢回复，我这边的应用场景是对于一个sqlite的文件，我会再使用完之后给删除掉然后重新建立。
但是现在由于一直占用着长连接，所以导致我无法删除。
另外。IFreeSql中并没有找到Dispose方法呢，我尝试在freeSql.ADO中释放，也失败了。代码如下：
freeSql.Ado.SlavePools.ForEach(t => { try { t.Dispose(); } catch { } });
try { freeSql.Ado.MasterPool.Dispose(); } catch { }

**Comment by 2881099** [comment]
升级到新版本有这个方法，关注一下更新日志：https://github.com/2881099/FreeSql/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

**Comment by LoveAuggie** [comment]
多谢~已解决~~

**Comment by AtlantisDe** [comment]
> 多谢~已解决~~

!!! 解决了 都不粘贴下代码啊..学会考虑其他人啊..养成分享习惯啊.
