### ISSUE TITLE
FreeSql 批量插入返回自增id

### ISSUE THREAD

**Issue by zhujinhu21** [2881099/FreeSql#58]
FreeSql 提供单条和批量插入数据的方法，在特定的数据库执行还可以返回插入后的记录。
可以在sql server 批量插入数据后返回插入后的主键自增id吗

**Comment by 2881099** [comment]
可以，用仓储或DbContext试试
数组

var repo = fsql.GetRepositrty\<T, int\>();
repo.Insert(数组)

自增值会付给数组的每个实体
