### ISSUE TITLE
文档显示出现问题。

### ISSUE THREAD

**Issue by luoyunchong** [2881099/FreeSql#65]
![image](https://user-images.githubusercontent.com/18613266/60397281-d186cb00-9b7d-11e9-92c4-044dd4c73a83.png)

文档显示上出现问题，http://freesql.net/doc?id=6，不只是这一处，好些都有问题。

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/FreeSql入门
这个是文档中心，官网内容还没建好

**Comment by luoyunchong** [comment]
好的，那我看wiki。
