### ISSUE TITLE
连接MYSQL出问题，引用了provide.mysql了，但是还是提示不行

### ISSUE THREAD

**Issue by niunan** [2881099/FreeSql#72]
连接MYSQL出问题，引用了provide.mysql了，但是还是提示不行
 
![TIM图片20190715225658](https://user-images.githubusercontent.com/7498393/61228754-7944f100-a759-11e9-99db-fc60914635d0.png)

**Comment by 2881099** [comment]
bin目录下有吗

**Comment by 2881099** [comment]
截图看下，检查文件权限

**Comment by 2881099** [comment]
不知道你用的什么版本nuget，如果是老版本，这样的结构不行，老版本语言web项目引用才会进入bin目录。

推荐使用新的nuget管理包，可循环依赖安装，不用每个项目都引用一次

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/issues/51

看下这个里面介绍的设置

**Comment by niunan** [comment]
可以了。。我按链接里的改nuget管理包的新方式不行，还是得在web层引用了freesql和provide mysql，
我的项目是最简单的三层（可能三层都不算）WEB,DAL,MODEL，其中所有的数据库操作全是放在DAL层的。。

**Comment by 2881099** [comment]
嗯，asp .net 好像是不行，core就可以，winform也可以
