### ISSUE TITLE
查询出来的值与数据库中的值不一致

### ISSUE THREAD

**Issue by WuMortal** [2881099/FreeSql#76]
版本：
FreeSql.Provider.MySql  0.6.11
FreeSql.Repository 0.6.11

MySql  8.0.16

dotnet core 2.2.0

实体：
![Snipaste_2019-07-23_21-58-24](https://user-images.githubusercontent.com/25811487/61718654-03aed580-ad96-11e9-86b6-611ea681891f.png)

出现值不一致字段名：`Type`

执行的SQL 语句：
![Snipaste_2019-07-23_22-04-12](https://user-images.githubusercontent.com/25811487/61718736-23de9480-ad96-11e9-85ea-070c2b583aa6.png)

数据库中执行的结果：
![Snipaste_2019-07-23_22-04-52](https://user-images.githubusercontent.com/25811487/61718703-14f7e200-ad96-11e9-9cec-4be04b05ae3e.png)

仓储返回的结果：
![Snipaste_2019-07-23_22-12-55](https://user-images.githubusercontent.com/25811487/61719197-0b22ae80-ad97-11e9-9e80-ca6da52942c7.png)

![Snipaste_2019-07-23_22-16-55](https://user-images.githubusercontent.com/25811487/61719476-98660300-ad97-11e9-8cbc-370eb36c0837.png)

**Comment by WuMortal** [comment]
是我类型设为小了 tinyint(1)，改为 tinyint(2) 就行了

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e6%9b%b4%e6%96%b0%e6%97%a5%e5%bf%97

好的，有空升下级
