### ISSUE TITLE
类型判断不准确

### ISSUE THREAD

**Issue by lyg1949** [2881099/FreeSql#78]
比如
`
Object obj = new Person();
_fsql.Insert(obj.ToSql()
`
sql语句是
`
INSERT INTO "Object"() VALUES()
`
而不是
`
INSERT INTO "Person"() VALUES()
`

我看了一下代码，在provider中的_table初始化用的是 typeof(T1)，是否可以改在使用source中具体对象的GetType方法来初始化_table呢，这样就可以获取其真正的Type了。

**Comment by lyg1949** [comment]
或者给增删改查都增加一个重载，接受一个具体的对象为参数，该重载可以根据对象来判断数据的类型，这样就不需要用户手动指定了。

主要是有些时候用户在调用增删改查等方法时并不知道T1具体的类型

**Comment by 2881099** [comment]
Object obj = new Person(); 
_fsql.Insert(obj).AsType(typeof(Person)).ToSql();

这样就对了，原因：

现在支持弱类型操作，所以不能直接 GetType 来对目标实体操作

**Comment by 2881099** [comment]
FreeSql.AdminLTE 用到了这个操作

**Comment by lyg1949** [comment]
多谢！@2881099

**Comment by lyg1949** [comment]
> Object obj = new Person();
> _fsql.Insert(obj).AsType(typeof(Person)).ToSql();
> 
> 这样就对了，原因：
> 
> 现在支持弱类型操作，所以不能直接 GetType 来对目标实体操作

不好意思，再问一个问题。

Insert方法可以通过AsType来指定类型，我试了一下确实可以；但是Update、Delete和Select好像没有AsType可以用，请问其他三种操作可以有其他方法指定类型吗？

**Comment by lyg1949** [comment]
找到了，原来其他几个方法需要先指定类型为Object之后才可以调用AsType来指定动态类型，和Insert不一样。

**Comment by LightCHY** [comment]
> 找到了，原来其他几个方法需要先指定类型为Object之后才可以调用AsType来指定动态类型，和Insert不一样。

是咋写的呢？

**Comment by 2881099** [comment]
> > 找到了，原来其他几个方法需要先指定类型为Object之后才可以调用AsType来指定动态类型，和Insert不一样。
> 
> 是咋写的呢？

fsql.Update<object>().AsType(实际的实体类型)

**Comment by LightCHY** [comment]
> > > 找到了，原来其他几个方法需要先指定类型为Object之后才可以调用AsType来指定动态类型，和Insert不一样。
> > 
> > 
> > 是咋写的呢？
> 
> fsql.Update().AsType(实际的实体类型)

假如这种更新方式按动态类型该怎么改：fsql.Update<Topic>().Set(a => new Topic {Clicks = a.Clicks + 1,Time = DateTime.Now}).Where(a => a.Id == 1).ExecuteAffrows();
我尝试后提示Where中不包含Id定义

**Comment by 2881099** [comment]
@LightCHY  你已经指明了 Topic，和楼主不一样

**Comment by LightCHY** [comment]
> @LightCHY 你已经指明了 Topic，和楼主不一样

fsql.Update<object>("2f0f744dd37045b9be3e7dbfb615c178").AsType(typeof(AppStoreModel)).Set(a => new AppStoreModel{ Name = "Phoenix" })，尝试这样写压根不执行

**Comment by 2881099** [comment]
@LightCHY 
 fsql.Update\< object >()
.AsType(typeof(AppStoreModel))

.WhereDynamic("2f0f744dd37045b9be3e7dbfb615c178")

.Set(a => new AppStoreModel{ Name = "Phoenix" })

注意先后顺序，不生效是因为 where 没作用。因为不是在 AsType 之后给的条件。

**Comment by LightCHY** [comment]
> @LightCHY
> fsql.Update< object >()
> .AsType(typeof(AppStoreModel))
> 
> .WhereDynamic("2f0f744dd37045b9be3e7dbfb615c178")
> 
> .Set(a => new AppStoreModel{ Name = "Phoenix" })
> 
> 注意先后顺序，不生效是因为 where 没作用。因为不是在 AsType 之后给的条件。
修改为这样：var i = fsql.Update<object>()
                .AsType(typeof(AppStoreModel))
                .Set(a => new { Name = "Phoenix" })
                .WhereDynamic(new { Id = "2f0f744dd37045b9be3e7dbfb615c178" })
                .ExecuteAffrows();
还是未能运行

**Comment by 2881099** [comment]
.SetDto(a => new { Name = "Phoenix" })
这样呢

**Comment by LightCHY** [comment]
> .SetDto(a => new { Name = "Phoenix" })
> 这样呢

试了下，也未能执行

**Comment by 2881099** [comment]
@LightCHY 

我开电脑测试了没问题：

```c#
var updateSql = g.sqlite.Update<object>()
    .AsType(typeof(testInsertNullable))
    .SetDto(new { str1 = "xxx" })
    .WhereDynamic(1)
    .ToSql();
```

```sql
UPDATE "testInsertNullable" SET "str1" = @p_0 
WHERE ("Id" = 1)
```

**Comment by LightCHY** [comment]
> @LightCHY
> 
> 我开电脑测试了没问题：
> 
> ```cs
> class testInsertNullable
> {
>     [Column(IsNullable = false, IsIdentity = true)]
>     public long Id { get; set; }
> 
>     [Column(IsNullable = false)]
>     public string str1 { get; set; }
>     [Column(IsNullable = false)]
>     public int? int1 { get; set; }
>     [Column(IsNullable = true)]
>     public int int2 { get; set; }
> }
> 
> var updateSql = g.sqlite.Update<object>()
>     .AsType(typeof(testInsertNullable))
>     .SetDto(new { str1 = "xxx" })
>     .WhereDynamic(1)
>     .ToSql();
> ```
> 
> ```sql
> UPDATE "testInsertNullable" SET "str1" = @p_0 
> WHERE ("Id" = 1)
> ```
噢，那我正调试下，谢谢！！！

**Comment by LightCHY** [comment]
@2881099 使用WhereDynamic一个PK条件是可以，由于定义的模型是复合主键，所以没成功。请教下如果是复合主键该如何写？

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/95568349-b2e8d280-0a56-11eb-8b81-0300b8096cf4.png)

传入动态条件，如：主键值 | new[]{主键值1,主键值2} | TEntity1 | new[]{TEntity1,TEntity2} | new{id=1}

**Comment by luoyunchong** [comment]
@LightCHY 
```
new{id=1,otherid=2} 试试。
```
不行就换 

![image](https://user-images.githubusercontent.com/18613266/95569088-aadd6280-0a57-11eb-9f1e-6c29edced17b.png)
```
        /// <summary>
        /// 原生sql语法条件，Where("id = ?id", new { id = 1 })<para></para>
        /// 提示：parms 参数还可以传 Dictionary&lt;string, object&gt;
        /// </summary>
        /// <param name="sql">sql语法条件</param>
        /// <param name="parms">参数</param>
        /// <returns></returns>
        TSelect Where(string sql, object parms = null);
```

**Comment by LightCHY** [comment]
> @LightCHY
> 
> ```
> new{id=1,otherid=2} 试试。
> ```
> 
> 不行就换
> 
> ![image](https://user-images.githubusercontent.com/18613266/95569088-aadd6280-0a57-11eb-9f1e-6c29edced17b.png)
> 
> ```
>         /// <summary>
>         /// 原生sql语法条件，Where("id = ?id", new { id = 1 })<para></para>
>         /// 提示：parms 参数还可以传 Dictionary&lt;string, object&gt;
>         /// </summary>
>         /// <param name="sql">sql语法条件</param>
>         /// <param name="parms">参数</param>
>         /// <returns></returns>
>         TSelect Where(string sql, object parms = null);
> ```

这个得知道映射的Attribute值吧，我试试
