### ISSUE TITLE
如何获取失败原因？

### ISSUE THREAD

**Issue by lyg1949** [2881099/FreeSql#79]
比如Insert抛出异常或者ExecuteAffrows返回的结果和预期的不一样，怎么判断原因呢？是数据结构不对？还是数据库失去连接？

**Comment by 2881099** [comment]
Exception错误

1。链接不可用
2，返回ado.net原始错误

正常返回影响的行数

**Comment by lyg1949** [comment]
链接不可用这个错误在运行时如何判断？是具体的字符串还是特定的code？

**Comment by 2881099** [comment]
语法正常，或者运行时数据都正常的情况下，其他错误：

1、【127.0.0.1/3306】状态不可用，等待后台检查程序恢复方可使用。Connection not ....
> 与数据库断开连接后，会一直报这个错误，直到恢复后正常

2、ado.net 执行错误，这个是原始错误对话，有可能是 SocketException，也可能是 SqlException

**Comment by lyg1949** [comment]
多谢！

如果提供自定义的异常，通过代码来指示错误原因的话，对开发人员来说会更友好，这样从message中分析还是麻烦些。

**Comment by 2881099** [comment]
这点确实，多数错误来自ado.net底层，底层也没有错误代码。
