### ISSUE TITLE
一般性问题

### ISSUE THREAD

**Issue by syzhuang** [2881099/FreeSql#80]
页面：
https://github.com/2881099/FreeSql/wiki/FreeSql%e5%85%a5%e9%97%a8

查询

var blogs = fsql.Select<Blog>
    .Where(b => b.Rating > 3)
    .OrderBy(b => b.Url)
    .Skip(100)
    .Limit(10) //第100行-110行的记录
    .ToList();
	
应为：	

var blogs = fsql.Select<Blog>()
    .Where(b => b.Rating > 3)
    .OrderBy(b => b.Url)
    .Skip(100)
    .Limit(10) //第100行-110行的记录
    .ToList();

**Comment by 2881099** [comment]
好的，谢谢提醒。

**Comment by 2881099** [comment]
已更新
