### ISSUE TITLE
讨论：整数除法的语义建议

### ISSUE THREAD

**Issue by fawdlstty** [2881099/FreeSql#85]
```csharp
List<tb_xxx> _list = Program.sql_conn.Select<tb_xxx> ().Where (_o => _o.id / 10000 == 121212 / 10000).ToList ();
```
_o.id为int类型。这行代码在表达式语义上含义为，查询_o.id在万位及以上等于12的值，但实际生成的sql将语义变为，查询_o.id除以10000后等于12.1212的值。
经验证发现，mysql语句将除法标记为“/”，然而mysql中整数除法使用“div”云算符。
解决方式是套一层Math.Floor ()
建议是使sql语义完全等同表达式的语义，即整数除法单独考虑云算符

**Comment by 2881099** [comment]
我在考虑，有没有不需要整除的需求

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/64402689-57f0e900-d0a8-11e9-9e8c-0027cf98e8aa.png)

万一不想整除咋办，先乘 1.0 ？

**Comment by fawdlstty** [comment]
> 万一不想整除咋办，先乘 1.0 ？

赞同，另外浮点型数据做除法也不整除

**Comment by fawdlstty** [comment]
或者`a => a.id / (double) 10000`

**Comment by 2881099** [comment]
整数还好，负数有坑，产生的sql会比较复杂。

c# 10/3=3, 10/-3=-3
c# Math.Floor(3.33)=3, Math.Floor(-3.33)=-4

sql floor(3.33)=3, floor(-3.33)=-4

所以转成sql后，除了要先abs再floor取整，然后还要判断是否为负数。整个操作下来略显复杂。。

**Comment by fawdlstty** [comment]
所以直接整除就没问题了，经测试`select 10 div -3;`，结果为-3

**Comment by 2881099** [comment]
OK，了解了，除了 mysql/oracle 要处理，其他数据库 / 都是整除

mysql 处理为 div，oracle 处理为 trunc
