### ISSUE TITLE
MySql的datetime,timestamp类型和.net的DateTimeOffset的映射问题。

### ISSUE THREAD

**Issue by liuguiyou** [2881099/FreeSql#87]
遇到一个问题
MySql的数据库字段类型是datetime
实体类的字段类型是DateTimeOffset，这个不能更改为DateTime类型
读取数据时会报类型转换异常
InvalidCastException: Invalid cast from 'System.Int32' to 'System.DateTimeOffset'.
FreeSql.Internal.CommonProvider.Select0Provider<TSelect, T1>.ToListAfPrivateAsync(string sql, GetAllFieldExpressionTreeInfo af, ValueTuple<string, ReadAnonymousTypeInfo, List<object>>[] otherData)

**Comment by 2881099** [comment]
数据库的值是什么，类型是datetime？

实体类上的DateTimeOffset有没有设置特性

**Comment by liuguiyou** [comment]
谢谢回复，实体类和相关代码如下
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace Artech.Identity
{
    /// <summary>
    /// 用户
    /// </summary>
    [Table("user")]
    public class ApplicationUser
    {
        [Column("id")]
        [Key]
        public  long Id { get; set ; }

        [Column("email")]
        public  string Email { get ; set ; }

        [Column("normalized_email")]
        public  string NormalizedEmail { get; set ; }

        [Column("user_name")]
        public  string UserName { get; set ; }

        [Column("phone_number")]
        public  string PhoneNumber { get; set; }

        [Column("access_failed_count")]
        public  int AccessFailedCount { get; set; }

        [Column("concurrency_stamp")]
        public  string ConcurrencyStamp { get; set ; }

        [Column("email_confirmed")]
        public  bool EmailConfirmed { get ; set; }

        [Column("Lockout_enabled")]
        public  bool LockoutEnabled { get ; set ; }

        [Column("lockout_end")]
        public  DateTimeOffset? LockoutEnd { get; set; }

        [Column("normalized_user_name")]
        public  string NormalizedUserName { get; set ; }

        [Column("password_hash")]
        public  string PasswordHash { get; set; }

        [Column("phone_number_confirmed")]
        public  bool PhoneNumberConfirmed { get; set; }

        [Column("security_stamp")]
        public  string SecurityStamp { get ; set ; }

        [Column("two_factor_enabled")]
        public  bool TwoFactorEnabled { get ; set ; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Column("created_by")]
        public long? CreatedBy { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("created_on")]
        public DateTimeOffset? CreatedOn { get; set; }

        /// <summary>
        /// 用户名称(显示用)
        /// </summary>
        [StringLength(256)]
        [Column("nick_name")]
        public string NickName { get; set; }

        /// <summary>
        /// 数据状态
        /// </summary>
        [Column("state")]
        public int State { get; set; } = 1;

        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(256)]
        [Column("description")]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// 头像
        /// </summary>
        [Column("avatar")]
        public string Avatar { get; set; }
    }
}

var fsql = new FreeSql.FreeSqlBuilder()
                .UseConnectionString(FreeSql.DataType.MySql, "Data Source=127.0.0.1;Port=3306;User ID=root;Password=root;Initial Catalog=aspnet;Charset=utf8mb4;SslMode=none;Max pool size=100")
                .UseAutoSyncStructure(false) //自动同步实体结构【开发环境必备】
                .Build();

            fsql.Aop.ConfigEntity = (s, e) =>
            {
                var attr = e.EntityType.GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.Schema.TableAttribute), false).FirstOrDefault() as System.ComponentModel.DataAnnotations.Schema.TableAttribute;
                if (attr != null)
                {
                    e.ModifyResult.Name = attr.Name;
                }
            };

            fsql.Aop.ConfigEntityProperty = (s, e) =>
            {
                var notmappedAttr = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute>(false);
                if (notmappedAttr != null)
                {
                    e.ModifyResult.IsIgnore = true;
                    return;
                }

                // 如果加上这段代码不会出错，但是感觉会有副作用，觉得FreeSql应该默认支持才对
                //if (e.Property.PropertyType == typeof(DateTimeOffset) || e.Property.PropertyType == typeof(DateTimeOffset?))
                //{
                //    e.ModifyResult.MapType = typeof(string);
                //}

                if (e.Property.GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.KeyAttribute), false).Any())
                {
                    e.ModifyResult.IsPrimary = true;
                }

                var columnAttr = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.Schema.ColumnAttribute>(false);
                if (columnAttr!=null)
                {
                    if (!string.IsNullOrEmpty(columnAttr.Name))
                    {
                        e.ModifyResult.Name = columnAttr.Name;
                    }

                    if (!string.IsNullOrEmpty(columnAttr.TypeName))
                    {
                        e.ModifyResult.DbType = columnAttr.TypeName;
                    }
                }

                var generatedAttr = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedAttribute>(false);
                if (generatedAttr != null)
                {
                    if(generatedAttr.DatabaseGeneratedOption == System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)
                    {
                        e.ModifyResult.IsIdentity = true;
                    }
                    else
                    {
                        e.ModifyResult.IsIgnore = true;
                    }
                }
            };

var users = await freeSql.Select<ApplicationUser>().Take(5).OrderBy(u => u.UserName).ToListAsync();

数据库脚本

create table `user` (
	`id` bigint (20),
	`access_failed_count` int (11),
	`concurrency_stamp` varchar (300),
	`email` varchar (768),
	`email_confirmed` tinyint (1),
	`Lockout_enabled` tinyint (1),
	`lockout_end` datetime ,
	`normalized_email` varchar (768),
	`normalized_user_name` varchar (384),
	`password_hash` varchar (1500),
	`phone_number` varchar (300),
	`phone_number_confirmed` tinyint (1),
	`security_stamp` varchar (300),
	`two_factor_enabled` tinyint (1),
	`user_name` varchar (768),
	`nick_name` varchar (768),
	`created_by` bigint (20),
	`created_on` datetime ,
	`state` int (11),
	`description` varchar (3000),
	`avatar` varchar (900)
); 
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('91','0','9cc2e380-2df0-4479-91d5-80ef7d0f803a','ironworm@hotmail.com','0','1',NULL,'IRONWORM@HOTMAIL.COM','IRONWORM@HOTMAIL.COM','AQAAAAEAACcQAAAAEPsfXkPs34Wj38kwo/VI+z2OWuhL+Mmni/M8bk6WNb4lR0MnIv58HxDbWt16z5AMQg==',NULL,'0','2ZV53JK75CGDFJ4IK2C5KLMITSKCQRC6','0','ironworm@hotmail.com',NULL,NULL,NULL,'1',NULL,NULL);
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('92','0','1a3939fb-c1a5-48d4-890c-5140ac94cf96','506927608@qq.com','1','1',NULL,'506927608@QQ.COM','506927608@QQ.COM','AQAAAAEAACcQAAAAEJcd2rT8u3mkqLHFxQ91E6neA8EUrjHlXeQnBFY+c5gt3pmkY27g0hvb5L7kGsPtCQ==',NULL,'0','NLSUIAQUTELZBVYRCUYB4WWF5WCZQIIG','0','506927608@qq.com','A',NULL,NULL,'1','a','https://img003.fview.cn/images/f4d2350f298c46d69778eea20328e822.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('93','0','70ee46af-3490-437b-8b92-bf1daa6745d8',NULL,'0','1',NULL,NULL,'MRHOU','AQAAAAEAACcQAAAAEAFr7LBLnOCfkLp+J2eNk2v1dbpc4WvrSlwpsfc2G8AJErNydQpht/0p6FRDX0ZsrA==',NULL,'0','6UC4ZKK2BBAMV3DNQSWKTZRIKAGVS2FX','0','MrHou','侯胜利','92','2019-06-11 09:05:48','1','123456789',NULL);
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('94','0','54e60644-eaf6-4617-b515-318ea375a20f',NULL,'0','1',NULL,NULL,'FADMIN','AQAAAAEAACcQAAAAEK1eOE2IGlBS1nemHzBf/AxEtGgwPurW+t2EwHkElJAU3rurs3Ij+6yTu4fxCa0QWA==',NULL,'0','HZRKBV6CSE3PKOFWP7UG536KQKRETUMQ','0','fadmin','FAdmin','92','2019-07-05 02:54:23','1','fadmin  123456','https://img003.fview.cn/images/a79ab0daa6644f158939d45c2a1a79b0.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('96','0','3b974d25-13e3-417f-9c19-60f4afdcfc1f','1149647837@qq.com','0','1',NULL,'1149647837@QQ.COM','U96','AQAAAAEAACcQAAAAEMOGDVU2rDZfrv3PXVugUqzA2lJsp9+kQmhSjSN1fkLO0OfYY+MFPurezQAuT/B9rQ==','','1','S4QLSXSL2HAJICEKDANPNJYBP5EZCLQO','0','u96','王6we建',NULL,'2019-07-10 06:02:04','1','手机达人打打打打啊打打打打打','https://img003.fview.cn/avatar/945062e88b3b4bd5942a229fc6ec34ca.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('97','0','c14f2e64-b919-4182-9579-bf83523cab26','31830453@qq.com','0','1',NULL,'','U97','AQAAAAEAACcQAAAAENuWro3i6NwwH+MI1GCFkXf3eACj/JyPYdZJX4ZPOQlMdCNdV9KcESsLyG3Q32cbfQ==','','0','GE2ZUOWD4HN6XLA5F76C6GD2KHINKZ7J','0','u97','locus',NULL,'2019-07-10 10:33:51','1','Developer','https://img003.fview.cn/avatar/b4599bcce8e840e8af2359187fcabcb9.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('98','0','590fa02a-5267-4efb-9057-340d56246921','ironwor@hotmail.com','0','1',NULL,'IRONWOR@HOTMAIL.COM','U98','AQAAAAEAACcQAAAAEPXw/DN/jXVGeDw0BeLGsYCKmR8TN+Cgx7qbj+T9g0pfdVr2WIyj1zZFvM8izevQiw==','13717724698','1','NU44QSHPF2SD4MVDCWTRRV2PKJOTEKPB','0','u98','abel',NULL,'2019-07-15 03:07:44','1','大Vvv','https://img003.fview.cn/avatar/47796e5e804149f498286131f1ecd41e.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('99','0','9851f4e4-8c9f-4d70-849c-b2ee52bfb0fe',NULL,'0','1',NULL,NULL,'SEPTILLION','AQAAAAEAACcQAAAAEPOXCzNd+yEKxaFJ+5BnWF56OFFPJy6dwFgOHZMjfN+qTKiMIJcbV0zWPykiC+yFDQ==',NULL,'0','DQV2IZNBHRJIL3UVY447BGURDJ6NQWH5','0','Septillion','王跃琨','94','2019-07-17 11:22:46','1','Digital Asshole','https://img003.fview.cn/images/130eea73878248559fa9e20e6a15f06c.JPG');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('74835526674284544','0','134b83e6-0949-4cec-ad2f-01ee9c1430ac',NULL,'0','1',NULL,NULL,'U74835526674284544',NULL,NULL,'0','O47GTYBXYGHL57IMD5CKE6IYPJLOFPMF','0','u74835526674284544','侯胜利',NULL,'2019-07-26 12:09:39','1','','https://img003.fview.cn/avatar/5125a084c817426d87e06ed1d2fdcac3.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('76230463764561920','0','a74578b5-a55b-4afd-9367-2e9de69ec15f','912750135@qq.com','0','1',NULL,'912750135@QQ.COM','U76230463764561920','AQAAAAEAACcQAAAAEJ84ZTSn7V9LkhoNmF7uotcQAEx8JISVCRMwAF+WCh8kYzKY7vX5+tp79vIzXyhE3w==','18811465574','1','KXK6JY4FY64X6KZO2IF7KMEM3LXHGUVM','0','u76230463764561920','王2',NULL,'2019-07-30 08:32:38','1','你猜猜看喽  404','https://img003.fview.cn/avatar/7e5b0433df4747eebf949ae2f219ee6f.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('76233691482816512','0','3137594b-b482-45d6-85be-3c5e120eeeb3','31830453@qq.com','0','1',NULL,'31830453@QQ.COM','U76233691482816512','AQAAAAEAACcQAAAAEDXX4t81ekbzOO5nSsHd1sv/rsI+XAprEJ29yWTcrO6noWC78rJAiox6HZT0BuDWNQ==','17610175201','1','MYPDEUTA3LSKUGF3QESRZ42QAYTMAE4S','0','u76233691482816512','locus',NULL,'2019-07-30 08:45:28','1','','https://img003.fview.cn/avatar/aa8c3c710fba4fe999994d46b3a68dc0.JPG');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('76283433499754496','0','42340ed8-1012-4c55-b81d-a02f80970a1a','699350@qq.com','0','1',NULL,'699350@QQ.COM','U76283433499754496','AQAAAAEAACcQAAAAEFfA2es0VBetXlHWr+aZ5+b08h4B8/A8cEYDGEyUize2l48c9FaXSVH6nIuL3TJndw==','18611281106','1','777EVGNCNCZYOTQHXVRIY32NQX7JTJIM','0','u76283433499754496','鹰哥',NULL,'2019-07-30 12:03:07','1','能用技术解决的不用人力','https://img003.fview.cn/images/55698d8882e043029bb6064dc5fc21fb.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('77305065500573696','0','08236d50-a120-4b28-ab04-12a7496370b0',NULL,'0','1',NULL,NULL,'U77305065500573696',NULL,NULL,'0','EF324ELEI4DUJM4POU6ZHPJZNFVG6DNP','0','u77305065500573696','彭林',NULL,'2019-08-02 07:42:43','1','','https://img003.fview.cn/images/214fa72bf1be4dc0b9b4ded2a2d93759.jpg');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('77332339646005248','0','079b6cb1-50ec-4d79-badb-b3194e764f54','2028654512@qq.com','0','1',NULL,'2028654512@QQ.COM','U77332339646005248','AQAAAAEAACcQAAAAEFId5DE3EebWrjIp9+LJPRnvVzBolq/UBeV9M5xZy0rwwfu46NHHogg/JF/1D7Irkg==','18610060088','1','M5N52IISPOC7JJLF7SWG6PFXLW7DJFY5','0','u77332339646005248','风中云语',NULL,'2019-08-02 09:31:06','1','苹果配件爱好者','https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTK4ZVUCL6zw7eABAaibdTVfKbPZumQT6tR1ZUboibRWESdjj1jDENpkqCFAnnKKic9ApMzlcD3CQgyXQ/132');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('78840649981362176','0','3c74a6d6-0039-4785-bcdb-466f04bed5dc','frankseptillion@msn.cn','0','1',NULL,'FRANKSEPTILLION@MSN.CN','U78840649981362176','AQAAAAEAACcQAAAAEOOuoS+tXFgEJw85MWFhoLJ++mvwNeGvUicTe/CY2VC/cR2Nb9JNIICmqsgLDRaIvw==','17610275926','1','UC34I44CC5SBWR5VEOIZY6EYZCIPW54J','0','u78840649981362176','Elite Controller',NULL,'2019-08-06 13:24:35','1','','https://wx.qlogo.cn/mmopen/vi_32/miaJkQmc7LXVcgLkLrjgDiaUsqnnzRciaicGoaGVVVSL64kAe7tVIPHCWvEGTicj21jgjJvwtoFibCk1Ngic9P7UrGtYQ/132');
insert into `user` (`id`, `access_failed_count`, `concurrency_stamp`, `email`, `email_confirmed`, `Lockout_enabled`, `lockout_end`, `normalized_email`, `normalized_user_name`, `password_hash`, `phone_number`, `phone_number_confirmed`, `security_stamp`, `two_factor_enabled`, `user_name`, `nick_name`, `created_by`, `created_on`, `state`, `description`, `avatar`) values('82290834053005312','0','0a7bca84-a860-4663-abee-591b6115bee9',NULL,'0','1',NULL,NULL,'U82290834053005312',NULL,NULL,'0','XYZJK5RRPE6ZB4HS6ON4PHM747D67QYK','0','u82290834053005312','小小',NULL,'2019-08-16 01:54:23','1','','https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIqo1orzWkppiatGarXHZWAfnH3boZpYma46ibX8GFf1IfHvfE5d98rCvDUqATIxukVHicVAtruGNPJg/132');

**Comment by 2881099** [comment]
待会我提交代码，让 DateTimeOffset 和 DateTime 转换互通。

![image](https://user-images.githubusercontent.com/16286519/64411597-1ff5a000-d0c0-11e9-8594-523a02646b58.png)

单元测试这样写的，使用习惯上有没有建议

**Comment by 2881099** [comment]
代码提交了，我这边测试通过了(crud)

c# 实体 DateTimeOffset 特性指明 MapType=typeof(DateTime)
数据库为 datetime

要不你先源码引入也测试一下，然后我再发包？

**Comment by liuguiyou** [comment]
还是会报异常，应该是数据为null时，缺少额外判断处理
An unhandled exception occurred while processing the request.
ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
FreeSql.Internal.CommonProvider.Select0Provider<TSelect, T1>.ToListAfPrivateAsync(string sql, GetAllFieldExpressionTreeInfo af, ValueTuple<string, ReadAnonymousTypeInfo, List<object>>[] otherData) in Select0Provider.cs, line 433

Stack Query Cookies Headers Routing
ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
FreeSql.Internal.CommonProvider.Select0Provider<TSelect, T1>.ToListAfPrivateAsync(string sql, GetAllFieldExpressionTreeInfo af, ValueTuple<string, ReadAnonymousTypeInfo, List<object>>[] otherData) in Select0Provider.cs
-
                    return Task.FromResult(false);
                }, CommandType.Text, sql, dbParms);
            }
            catch (Exception ex)
            {
                exception = ex;
                throw ex;
            }
            finally
            {
                var after = new Aop.CurdAfterEventArgs(before, exception, ret);
                _orm.Aop.CurdAfter?.Invoke(this, after);
            }
Test.WebApp.Controllers.TestController.Sql(IFreeSql freeSql) in TestController.cs
-
        [Route("sql")]
        public async Task<IActionResult> Sql([FromServices] IFreeSql freeSql)
        {
            var sql = freeSql.Select<ApplicationUser>().Take(5).OrderBy(u => u.UserName).ToSql();
            //var users = await freeSql.Select<ApplicationUser>().Take(5).OrderBy(u => u.UserName).Select(u => new { u.Id, u.NickName, u.UserName, u.CreatedOn }).ToListAsync();
            
            var users1 = await freeSql.Select<ApplicationUser>().Take(5).OrderBy(u => u.UserName).ToListAsync();
            return Ok(users1);
        }
    }
}

**Comment by liuguiyou** [comment]
建议在未来版本里添加可自定义的数据库原始值到dotnet类型的值转换器

如
                /// <summary>
        /// 值转换器
        /// </summary>
        public interface IValueConverter
        {
            /// <summary>
            /// 
            /// </summary>
            /// <param name="raw">数据库原始值</param>
            /// <returns>转换后的值</returns>
            object Convert(object raw);
        }

        public class ColumnAttribute : Attribute
        {
            // 此处可以设置自定义值转换器，当不为null时，在构建表达式树时使用此转换器处理数据库原始值
            public IValueConverter Converter { get; set; }
        }

**Comment by 2881099** [comment]
这样只能定义 read 读数据时的转换，还有写数据的转换。后续考虑加进来

目前默认的方式+ColumnAttribute.MapType 方式进行的映射，确实是 null 问题，测出来了

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/64422706-470b9c00-d0d7-11e9-87de-5a8e4d48033d.png)

错误是这样产生的。。不是为 null

**Comment by 2881099** [comment]
DateTime.Parse("0001-01-01 00:00:00.000") 不会报错，DateTimeOffset 不支持这个范围的数据

**Comment by 2881099** [comment]
[Column(MapType = typeof(DateTime?))]
public DateTimeOffset? dtosnullable_to_dt { get; set; }

测试属性 MapType = typeof(DateTime?)]，改成这样后正确

**Comment by 2881099** [comment]
new DateTimeOffset(DateTime.Parse("0001-01-01 00:00:00.000"), TimeSpan.Zero)

话说回来，这样就没问题，你认为怎么处理好？

**Comment by liuguiyou** [comment]
用你说的方式就行,一般情况下用DateTimeOffset类型表示数据库里保存的就是Utc时区的数据 
new DateTimeOffset(DateTime.Parse("0001-01-01 00:00:00.000"), TimeSpan.Zero)

**Comment by 2881099** [comment]
OK，TimeSpan.Zero 代码已经处理了，之后和其他功能一起发布

**Comment by liuguiyou** [comment]
又测试了下，  new DateTimeOffset(dateTime, TimeSpan.Zero)可能会产生异常，用new new DateTimeOffset(dateTime.Ticks, TimeSpan.Zero)可以避免异常

**Comment by 2881099** [comment]
收到

**Comment by 2881099** [comment]
v0.9.10 版本已发布
