### ISSUE TITLE
postgresql 分表 AsTable 表名大小写未正确转换

### ISSUE THREAD

**Issue by staneee** [2881099/FreeSql#89]
![image](https://user-images.githubusercontent.com/26987099/64513771-dc976d80-d31b-11e9-9e97-ff44c963d1a2.png)

![image](https://user-images.githubusercontent.com/26987099/64513733-c5588000-d31b-11e9-833c-bd08ab2976b6.png)

![image](https://user-images.githubusercontent.com/26987099/64513840-fdf85980-d31b-11e9-822b-9fd032a32434.png)

**Comment by 2881099** [comment]
nuget 包 v0.9.9 已发布，感谢支持

**Comment by staneee** [comment]
牛皮
