### ISSUE TITLE
Filter能否实现临时关闭操作？

### ISSUE THREAD

**Issue by LambertW** [2881099/FreeSql#9]
请问一下 ，是否可实现类型的方案？
``` c#

using(_itemRepository.DisableFilters("ISoftDelete")){


}

```

**Comment by 2881099** [comment]
我是想着orm.GetRepository()重新获取一个即可，你这个想法也挺好

**Comment by LambertW** [comment]
可以参考一下abp的做法。

``` C#
public IDisposable DisableFilter(params string[] filterNames)

		{

			var disabledFilters = new List<string>();

			foreach (var filterName in filterNames)

			{

				var filterIndex = GetFilterIndex(filterName);

				if (_filters[filterIndex].IsEnabled) {

					disabledFilters.Add(filterName);

					_filters[filterIndex] = new FilterConfiguration(filterName, false);

				}

			}

			return new DisposeAction(() => EnableFilter(disabledFilters.ToArray()));

		}

		public IDisposable EnableFilter(params string[] filterNames)

		{

			var enabledFilters = new List<string>();

			foreach (var filterName in filterNames)

			{

				var filterIndex = GetFilterIndex(filterName);

				if (!_filters[filterIndex].IsEnabled)

				{

					enabledFilters.Add(filterName);

					_filters[filterIndex] = new FilterConfiguration(filterName, true);

				}

			}

			return new DisposeAction(() => DisableFilter(enabledFilters.ToArray()));

		}



```

类似这样，若有计划实现，何时实现，能够给个时间？

**Comment by LambertW** [comment]
试过SQLsugar，发现隐藏问题太多。
目前你这个默认可实现过滤功能，挺方便的。

**Comment by 2881099** [comment]
abp vnext 做法有些不一样，刚才研究了一番。

我先尝试一下，有结果了在这里回复你。

**Comment by LambertW** [comment]
效率好高，感谢~

因为目前公司平台仍然无法使用.NET Core，我测试也是使用nfx4.6.1

预期是能够实现这种效果，
1. Entity继承ISoftDelete接口即可实现默认过滤功能，非逐个Entity进行配置；
2. using作用域可以实现多重启动/停用过滤，参见以下代码~
亦可参见`https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/test/Volo.Abp.TestApp/Volo/Abp/TestApp/Testing/SoftDelete_Filter_Tests.cs`的 `Should_Get_Deleted_Entities_When_Filter_Is_Disabled()`
``` c#
[Fact]
public void Count_ISoftDelete()
{
    var items = GetItemDemos(2);
    items[0].IsDeleted = true;
    items[1].IsDeleted = false;
    _itemDemoRepository.InsertRange(items);

    var count = _itemDemoRepository.Count();
    Assert.True(count == 1);
    using (_itemDemoRepository.DisableFilter("ISoftDelete"))
    {
        count = _itemDemoRepository.Count();
        Assert.True(count == 2);

        using ( _itemDemoRepository.EnableFilter("ISoftDelete"))
        {
            count = _itemDemoRepository.Count();
            Assert.True(count == 1);
        }
    }

    count = _itemDemoRepository.Count();
    Assert.True(count == 1);
}
```

**Comment by 2881099** [comment]
是的，现在两项都可以

临时禁用
using (repos1.DataFilter.Disable("test")) {
    //在这段中，repos1 之 test 过滤器失效
}

//repos1 之 test 过滤器重新生效

**Comment by 2881099** [comment]
freesql.repository提供的过滤器，不只做查询，还做数据验证

**Comment by LambertW** [comment]
明白，不过目前项目`Freesql,Repository`没有添加Tests，看上去有些抽象~
原功能及新功能增加，不太容易看得到效果

**Comment by 2881099** [comment]
Repository 目前是在示范项目内测试和使用的。

https://github.com/2881099/FreeSql/tree/master/Examples/repository_01

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/repository

仓储直接面向用户，提供的方法不多。

**Comment by 2881099** [comment]
仓储无非就是把 curd 集成起来，然后额外的增加优化使用功能

**Comment by LambertW** [comment]
今天刚刚下载下来您的代码，发现单元测试数量还是很高的，就是一片红..
是否集成一下对应的脚本~
![image](https://user-images.githubusercontent.com/12291760/54201061-bbd69280-4507-11e9-83d5-7b9da2fe722e.png)


Repository还有很多可以添加的内容呀~
为了减少搬砖的内容，ICreationTime, IModificationTime, UpdateUser这些通用的实现，都可以考虑如何在Repository中去实现~或者提供一下如何基于你的项目，进行开发~

**Comment by LambertW** [comment]
[https://github.com/docevaad/Chain/wiki/Audit-Rules](url)
[https://github.com/schotime/NPoco/wiki/Performing-Operations-during-Poco-events-(Insert,-Update,-etc)](url)
这个不一定适合Freesql，仅供拓展思路~

**Comment by 2881099** [comment]
测试项目中，g.cs 配置好数据库测试连接

**Comment by LambertW** [comment]
感谢指点，已经知道如何验证对应数据~谢谢
![image](https://user-images.githubusercontent.com/12291760/54201805-892d9980-4509-11e9-8469-1f16a9a82c09.png)

**Comment by 2881099** [comment]
Query 因为执行的 sql ，然后你的数据库没有 song 表，其他基本是好的
