### ISSUE TITLE
怎么记录每一次执行的SQL语句？

### ISSUE THREAD

**Issue by mylovefly001** [2881099/FreeSql#92]
怎么记录每一次执行的SQL语句？不用ToSQL方法，这个不方便。

**Comment by mylovefly001** [comment]
> 怎么记录每一次执行的SQL语句？不用ToSQL方法，这个不方便。

已解决。

**Comment by 2881099** [comment]
好的，几个地方可以，Aop.CurdAfter 或者Aop.CurdBefore 或者 FreeSqlBuilder.UseMonitorCommand
