### ISSUE TITLE
FreeSql最低版本支持是否可考虑升级net46?

### ISSUE THREAD

**Issue by LambertW** [2881099/FreeSql#94]
问题是这样的。
看到您写的`FreeSql.Extensions.BaseEntity`项目，原想试用一下，但是因为公司限制问题，目前使用的VS2015版本无法正常使用.net standard 2.0，所以此nuget包无法引用安装。

看了一下此项目引用了 `FreeSql`, `FreeSql.DbContext`，其中，内部使用的`AsyncLocal<T>`在.net 4.5中无法正常使用。导致`FreeSql.DbContext`中也有类似的`#if ns2.0`的写法。

是否有计划将完整项目升级至`netstandard2.0;net46`的打算？

**Comment by 2881099** [comment]
FreeSql, FreeSql.DbContext 这两个目前支持到了 net45，应该可以引用

**Comment by LambertW** [comment]
是的，`FreeSql.Extensions.BaseEntity`由这个项目，再看了一下原来的内部调用。

**Comment by 2881099** [comment]
BaseEntity 里面有个树型结构类没设计好，可能还会改

代码不多，你看看能不能直接用源码开发，😄

**Comment by LambertW** [comment]
嗯，也是好奇所有项目设置net45是不是有其他的一些考虑因素。

BaseEntity主要是为了体验一下。

**Comment by 2881099** [comment]
net45因为元组的语法，适配条件少，再低的话需要大量的编译条件，不划算

发布成net45包，使用46开发可以引用，也算是支持了metframework

另外，ns20可以被net461以上的项目引用

**Comment by LambertW** [comment]
谢谢答复~
