### ISSUE TITLE
FluentApi能否支持导航关系配置?

### ISSUE THREAD

**Issue by aaasssmnb** [2881099/FreeSql#96]
对于一些遗留系统,目前的默认约定难以实现,尤其是OneToMany和 ManyToOne
如果为所有实体加上特性又太多,而且另一方面也不希望污染到它们
当导航配置得不合格不止影响查询,也会影响到写入的逻辑
后续是否能通过外部手段支持导航的配置?
目前有哪些方法可以解决这些问题?

**Comment by 2881099** [comment]
好的，既然有需求，我来想办法支持吧。
目前导航配置只能约定，或特性。

**Comment by 2881099** [comment]
```csharp
fsql.CodeFirst.ConfigEntity<实体类>(a => a.Navigate(b => b.roles, null, typeof(多对多中间实体类)));
```

**Comment by aaasssmnb** [comment]
**点赞**
